### ISSUE TITLE
DEXBot wont place any orders

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#104]
A few users, myself included, have setup dexbot on windows, created a worker, all done correctly. With enough BTS for transactions and a balance of both assets but cant get dexbot to place any orders. Restarted various times, deleted worker and re added it. nothing seems to work. Also it shows no errors.

**Comment by CryptoKong** [comment]
after feedback from users (ive not tried myself), this was resolved by updating the config file to another node.

**Comment by MarkoPaasila** [comment]
Default node changed to node dedicated to DEXBot. I'll close this issue.
