### ISSUE TITLE
Add bot log to the GUI

### ISSUE THREAD

**Issue by mikakoi** [Codaone/DEXBot#11]
The GUI should have a place where all the logged messages are displayed.
Timestamp, bot name and the message should be displayed on a single log message.

**Comment by MarkoPaasila** [comment]
If I may suggest the following format for easy spreadsheet usage:
ACTION | ID | AMOUNT | ASSET | AMOUNT | ASSET | TIME
--------------------------------------
Place order | 1.2.34567 | -100.00000 | BTS | 12.34567 | USD | [datetime]
Fill order | [object id] | -50.00000 | BTS | 6.1604893 | USD | [datetime]
Cancel order | 1.2.34567 |  |  |  |  | [datetime]

**Comment by MarkoPaasila** [comment]
Or is this log intended more for troubleshooting, and would so contain connection problems and other info unrelated to strategy performance?

**Comment by MarkoPaasila** [comment]
I don't think the log needs to be accessible via gui. You only need it for troubleshooting, not normal operation, therefore it is enough if it can be opened from the directory. I my opinion this issue can be closed
