### ISSUE TITLE
Mac OSX - app crashes when entering wallet password

### ISSUE THREAD

**Issue by adamchavez** [Codaone/DEXBot#119]
## Expected Behavior
Expect that when password is entered here that the app should open:
![screenshot 2018-05-09 12 19 22](https://user-images.githubusercontent.com/387043/39832180-c0ac47ee-5383-11e8-9712-766ec48591a2.png)

## Actual Behavior
Once I enter my password, and hit enter, the app crashes.

## Steps to Reproduce the Problem

  1. Download the tar.gz file
  2. Double-click on DEXBot-gui Application file
![screenshot 2018-05-09 12 20 28](https://user-images.githubusercontent.com/387043/39832203-cc6b9b0c-5383-11e8-9acd-7a69b81e3a4f.png)

  3. Create a password to encrypt private keys
  4. Open up the app again, enter password, hit enter

## Specifications

  - Version: https://github.com/Codaone/DEXBot/releases/tag/0.1.16
  - OS: Mac OSX Sierra, 10.12.5

**Comment by crackfoo** [comment]
Same issue here on High Sierra 10.13.4

**Comment by MarkoPaasila** [comment]
@adamchavez and @crackfoo does it work with the latest release? If not, please try starting the application from command line and post any error messages from the console output. It will help. Thanks!

**Comment by crackfoo** [comment]
yes, latest version seems ok now.

Thanks
