### ISSUE TITLE
Don't reset orders until one or both of the orders have filled completely

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#121]
The current behavior for Relative Orders is to reset orders immediately when an order is touched; filled completely or partially. This isn't good, as there are bots that nibble on orders. So when the price actually reaches one's order, the orders are quickly removed and profits are not made to the full potential.

**Suggested change:**
Instead of resetting orders when `order changes or disappears`

reset orders only once `order disappears completely`

**Comment by mikakoi** [comment]
Issue resolved in 0.1.24
