### ISSUE TITLE
Exit cli gracefully tries to add new orders

### ISSUE THREAD

**Issue by juhanihaapala** [Codaone/DEXBot#136]
This came up when trying straggered orders with cli.

## Expected Behavior
All orders would be canceled and cli would exit.

## Actual Behavior
Every order cancel makes event change which seems to fire "order was filled" and then the worker tries to add new order (and when I didn't have balance other side, then it disabled the worker as many times) 

## Steps to Reproduce the Problem
  1. Set up a worker with straggered orders
  2. When orders are placed hit ctrl + c
  3. Log says canceling orders and then spawn events for every order

## Specifications

  - Version: 0.2.1
  - OS: Windows and Linux

**Comment by MarkoPaasila** [comment]
#237 should make Staggered Orders behave differently, as there is no initialization phase any more. I'll close this as obsolete and hopefully solved soon.
