### ISSUE TITLE
Staggered Orders should be left on the books when exiting dexbot-cli with ctrl+c

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#137]
As it's a strategy that makes profit even when not monitored. 

Placing orders might take anything from between a minute and several hours. It is terrible to wait for so long after having to restart the bot because of a bug or because of a change in strategy. Also it should be possible for the user to initiate the strategy, close DEXBot, and check after a week.

**Comment by bitfag** [comment]
I looked a bit at the related code. From my point of view, to implement this nicely, we need:

1. Implement a way to propagate events from cli.py to the worker job. At now, there is only job name propagated, like `kill_workers = worker_job(worker, worker.stop)`. What is needed is to pass some `kill_reason` to the worker so it can determine what to do.
2. worker.py: `def stop(self, worker_name=None, kill_reason=None)`, and inside this function `self.workers[worker].cancel_all(kill_reason=kill_reason)`
3. basestrategy.py: `def cancel_all(self, kill_reason=None):`
4. strategies/staggered_orders.py: define own method `def cancel_all(self, kill_reason=None):` like this:
```python
    def cancel_all(self, kill_reason=None):
        if kill_reason='SIGINT':
            pass
        else:
            if self.orders:
                self.cancel(self.orders)
```

So, to briefly summarize: we need a common way of propagating signals. Different strategies may implement own handlers for different signals. Some strategies should keep orders on INT. Another strategies may implement a special actions on SIGUSR2, and so on.
