### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by sirkbitt** [Codaone/DEXBot#138]
## Expected Behavior
The bot could be able to initalize itself using relative orders strategy.
The working of this strategy has been updated 5-8 hours ago.

## Actual Behavior
Here are python errors:
Traceback (most recent call last):
  File "dexbot/worker.py", line 75, in init_workers
  File "dexbot/strategies/relative_orders.py", line 38, in __init__
  File "dexbot/strategies/relative_orders.py", line 127, in check_orders
  File "dexbot/basestrategy.py", line 207, in get_order
TypeError: argument of type 'NoneType' is not iterable
So it seems to be an issue concerns NoneType objects related to kwargs.

## Steps to Reproduce the Problem

  1. Choose Relative Orders Strategy
  2. Set relative orders size and spread
  3. Save and push the green button
The same issue afflicts DEXBot-cli as well.

## Specifications

  - Version: 0.2.0 (both GUI and command line cli)
  - OS: MacOS X

**Comment by ihaywood3** [comment]
can you try again with 0.2.1?

**Comment by mikakoi** [comment]
Fix for this is now in the latest release.
