### ISSUE TITLE
Failed to install on gentoo as recommended in the docs

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#142]
## Expected Behavior

Success installation.

## Actual Behavior

```
% make install-user   
python3 -m pip install -r requirements.txt
ERROR: (Gentoo) Please run pip with the --user option to avoid breaking python-exec
Makefile:20: recipe for target 'pip' failed
make: *** [pip] Error 1
```

## Specifications

  - Version: d6e7f72e94aeb32f13440b8dfedc627393c99bab
  - OS: funtoo linux

**Comment by bitfag** [comment]
What about using `pipenv` to manage dependencies and installation? It's really neat!

**Comment by MarkoPaasila** [comment]
I would expect a gentoo user to manage to solve such a problem :-)
If you want to install pypi packages system wide, I think you need to do it as root (sudo). In general it's better to install anything using the --user switch just as the output suggests, so it doesn't mess up with the systems own package management.

**Comment by bitfag** [comment]
I actually installed dexbot in virtualenv.

**Comment by ihaywood3** [comment]
this is pretty nonstandard behaviour by gentoo (insisting pip always use --user)
One obvious solution is to install the dependencies manually using --user as it wants.
Supporting every linux distro isn't really doable. If you have limited linux knowledge please stick to ubuntu as per the docs.
If you want to use a different distro then we have to ask you to solve these problems yourself.

**Comment by MarkoPaasila** [comment]
I'll close this, referring to the fact that we can support only the most common setups...
