### ISSUE TITLE
Syntax error in code

### ISSUE THREAD

**Issue by deepeetoo** [Codaone/DEXBot#146]
## Expected Behavior
DEXBot starts up.

## Actual Behavior
DEXBot does not start up.

## Steps to Reproduce the Problem

  1. pull latest from Git
  2. make install-user
  3. run dexbot-gui

--> `.local/lib/python3.5/site-packages/dexbot-0.2.3-py3.5.egg/dexbot/strategies/staggered_orders.py", line 184
sell_price = center_price * math.sqrt(1 + increment spread)`

Should be **math.sqrt(1 + increment + spread)** ?

**Comment by MarkoPaasila** [comment]
LOL and thanks!

**Comment by mikakoi** [comment]
I've made a hotfix which fixes this issue. The fix can be found in 0.2.4
