### ISSUE TITLE
Relative order size for staggered orders

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#147]
With staggered orders I feel a strong desire to have relative order sizes for buy/sell orders. For example, I have low amount of base and huge amount of quote asset, so I want to place big sell orders and low buy ones. In further perspective this strategy will try to rebalance my assets.

**Comment by MarkoPaasila** [comment]
I think the most simple solution right now is to use Relative Orders to balance your portfolio first. In the future I would like such additional mechanisms included into Staggered Orders, but it needs to be well though out. The problem one is trying to solve is "how to best start one-sided", and having relative order sizes isn't necessarily the best solution.

**Comment by MarkoPaasila** [comment]
Having significantly different order sizes on opposite sides will make the strategy something else than _Staggered Orders_. After the full revision of the strategy, what it will do is take all profits entirely in the "lesser" asset and slowly achieve balance. If the user want to speed things up, he can use any other strategy to first aquire the other asset and then give the funds back to the _Staggered Orders_ worker. So the strategy will account for the situation where the user has much more of one asset, and it will fix it very slowly. That said, it will likely result in a good average price while balancing the assets, all while making profits in it's designed way.
