### ISSUE TITLE
Staggered orders should be recalculated / replaced whether config values were changed

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#149]
Related to dexbot-cli.

## Expected Behavior

Center price recalculated, old orders from database purged, new orders placed.

## Actual Behavior

Old orders from database placed.

## Steps to Reproduce the Problem

  1. Setup worker with staggered orders, launch, stop, exit.
  2. Manually change the `config.yml`, adjust amount, spread, increment, bounds.
  3. Start `dexbot-cli`
  4. dexbot will not respect config changes and will instead put the old orders from database.

## Specifications

  - Version: 0.2.4

**Comment by MarkoPaasila** [comment]
It seems to me that this should be the only case when Staggered Orders cancels all orders. Also it would probably make sense to cancel all orders if the worker is removed from the config.

**Comment by MarkoPaasila** [comment]
@bitfag Do you already have an idea how to do this? If so, do you want this issue assigned to you?

**Comment by bitfag** [comment]
Have some ideas, but I need to better study the code. Keep in unassigned for now, maybe later I will work on this.

**Comment by mikakoi** [comment]
There is no reason to implement a solution to this since the Easyconfig pull request adds a command "configure", it's main point is to replace config file manual edits.
