### ISSUE TITLE
Add edit bot feature

### ISSUE THREAD

**Issue by nikolaybaychenko** [Codaone/DEXBot#15]
Add a feature that allows editing bots

**Comment by MarkoPaasila** [comment]
Does this mean from the user perspective?

I assume that after editing the parameters the bot would proceed to simply cancel all previous orders and place new ones. The cost (of placing and cancelling orders) is very small and doing it like this is probably the most simple solution technically.

**Comment by nikolaybaychenko** [comment]
@MarkoPaasila Editing a bot will cancel all the orders, stop the bot and place new orders when you start the bot again.

**Comment by MarkoPaasila** [comment]
So what remains is history and what is not changed in configuration (name, account, etc)? Same as with "pausing" the bot.
