### ISSUE TITLE
Maintenance Logic implementation to GUI

### ISSUE THREAD

**Issue by lsji07** [Codaone/DEXBot#154]
## Expected Behavior
On clicking play the maintenance logic should be activated and the bot checking for new buys and sells according to the selected strategy, and if required delete existing unprofitable orders. If the strategy has be altered then all the orders should be deleted and new strategy implemented.

## Actual Behavior
On clicking play the all existing orders are cancelled and new orders are placed according to the current strategy.

## Steps to Reproduce the Problem

  1. Click Play
  2. Watch preexisting orders being cancelled.
  3. Watch new orders being placed.

## Specifications

  - Version: DEXBot-win64 using DEXBot-gui 0.2.3 as latest release
  - OS: Windows 10 Pro 64

**Comment by mikakoi** [comment]
This was fixed in 0.2.5, I'll close this once a release has been made from it.
