### ISSUE TITLE
Removing bots should not remove all orders of the bot account

### ISSUE THREAD

**Issue by mikakoi** [Codaone/DEXBot#16]
Currently when a bot is removed from the GUI all the orders of the bot account are canceled.
Change it so that only the orders made by the bot are removed.

**Comment by MarkoPaasila** [comment]
I don't think this is necessary. We can expect every instance to have a dedicated account with no additional activity or orders. That way we can keep things as simple as possible and avoid this issue and lots of others.

This is how I think it should work:
* If the user stops the bot (presses stop button), all open orders are cancelled
* If the user removes the bot, a modal asks whether he wants to cancel all orders or not
* If the user closes the software, all open orders remain.
