### ISSUE TITLE
Log file error?

### ISSUE THREAD

**Issue by lsji07** [Codaone/DEXBot#162]
## Expected Behavior

Operating the GUI version as always online and checking the dexbot.log for trades and any issues. 

## Actual Behavior
Running always online with faster buy/sell orders seems to create a log file issue when you hit the maximum size of the log file or another yet to be determined error. Bot stops working and stops trades.

## Steps to Reproduce the Problem

  1. Start GUI
  2. Run always on in either strategy with a lot of small lower value trades. low spread and intervals
  3. Bot fails and log is full...love to know why the bot fails in an error log. Assuming log file gets full and technical speak "spits it dummy out".

Expecting a separate warning/error log and trade log. Trade log "unlimited" entries, or split into smaller log files dependant upon file limitations. Discussed previously I assume?

No coding skills here so just let you know the issue I see.

## Specifications

  - Version: 0.2.3
  - OS: Win 64 Pro

**Comment by MarkoPaasila** [comment]
Did you run out of disk space?

#80 is an issue for saving only trade history, and it's not implemented yet.

**Comment by lsji07** [comment]
No I have 46.5Gb free on my C drive and keeping the bot files on a separate D drive 2TB (that is practically empty).

Could be the python binary not identifying my user name correctly when redirecting (my PC user name has a space). I read Python wobbles if spaces are not swopped out perfectly for underscores etc. If I can reproduce the error again I'll raise the issue again. Running 0.3.0 for now with latest binaries as the latest release. 

#80 seems a good idea and format for csv manipulation for checking over trades by hand. Assuming we are only talking about base to quote trade values currently. Example had USD/BTS.

If we are talking wishlist though, another few columns with strategy implemented (include settings) and Profit/loss to latest trade. 

Date, Action, ID, Quote, Amount, Base, Amount, Strategy, Amount, Spread, Increment, Lower bound, Upper bound,  Strategy Profit/Loss.
Example:
14/06/2018, Fill order, 1234566788, BTS, -100, USD, 6.5436, 14042018, Staggered, 10, 6%, 4%, 0.01, 0.05, +0.54251%

**Comment by MarkoPaasila** [comment]
Had the directory name been an issue, it wouldn't have written any log to begin with. So I think this was just one of the other pretty common crashes.

@mikakoi it seems to me that this isn't an error related to logging, but some other error that stopped trading and thus also logging. If you agree, would you mind closing this issue?

@lsji07 an exportable trade log will be implemented at some point. #80 
Next time you report a bug, please include the actual error message. It will help a lot. Thanks!
