### ISSUE TITLE
Installation on osx

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#167]
## Expected Behavior
Installation from command line succeeds with make install-user

## Actual Behavior
```
1 error generated.
error: Setup script exited with error: command '/usr/bin/clang' failed with exit status 1
make: *** [install-user] Error 1
```
## Steps to Reproduce the Problem

  1. Install dependencies ( I don't know which ) with homebrew
  2. git pull
  3. make install-user

## Specifications

  - Version: 0.3.0
  - OS: Mac osx (3 years old)

**Comment by mikakoi** [comment]
I found this from stackoverflow: https://stackoverflow.com/a/32741609
Can you try that?
