### ISSUE TITLE
Fix the need to install dependencies manually with "pip"

### ISSUE THREAD

**Issue by diogogomes** [Codaone/DEXBot#17]
**There are several dependencies that must be manually installed with `pip` because the compile script does not detect the dependencies installed with the system's package manager.**

I am trying to compile the code in **Xubuntu 16.04 LTS**, but after seeing problem #13, I think this is common in **distributions based on Debian**.

These problems are also detected in [xeroc/stakemachine](https://github.com/xeroc/stakemachine) repository.

Dependencies detected so far:
- **click-datetime**
- **pyqt5**

**One possible solution is to include `pip3 install --user PACKAGES` in the compile script.**

**Comment by mikakoi** [comment]
Fixed as of #22. Now you can use make to install dexbot. Or just simply install by hand with pip.
