### ISSUE TITLE
Staggered orders should not be cancelled on error

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#170]
## Actual Behavior

When error in staggered_orders worker is happen, it will cancel all orders from the market:

```python
     def error(self, *args, **kwargs):
         self.cancel_all()
         self.disabled = True
```

On next run reverse orders will be placed effectively selling all your funds. Should be fixed ASAP.

## Steps to Reproduce the Problem

  1. Add any error-producing code to the `def tick()` inside staggered_orders.py
  2. See worker error
  3. Remove error from the code
  4. Restart workers
  5. See how worker is selling everything
  6. Press Ctrl-Z immediately then kill worker with `kill -9`

## Specifications

  - Version: 0.2.7

**Comment by MarkoPaasila** [comment]
Yes I agree. This behavior was apparently inherited from Relative Orders, where I think orders should be cancelled if we aren't sure what's going on. But with staggered orders we don't care what's going on in the same manner. Thank you! Excellent observation!
