### ISSUE TITLE
Logger level does not being proparated to the 'dexbot.per_worker'

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#172]
Setting verbosity level via cli not working `./cli.py -v 4 run`

To check this add a few lines inside worker:

```python
    def tick(self, d):
        """ ticks come in on every block
        """
        self.log.debug('tick-tack: %s', self.worker_name)
        print(logging.getLogger('dexbot.per_worker').getEffectiveLevel())
        if self.recheck_orders:
            self.check_orders()
            self.recheck_orders = False
```

You will see the output is '20' which indicates INFO level.

This error happens due to error in logger initialization inside `dexbot/ui.py`.

**Comment by MarkoPaasila** [comment]
Does this affect only output to console/logfile, or also the logic of the bot?

**Comment by bitfag** [comment]
Only output is affected.
