### ISSUE TITLE
Staggered orders - asset balance reduces on one side

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#176]
## Expected Behavior
Both assets to slowly increase balance size

## Actual Behavior
One assets decreases in balance size

## Steps to Reproduce the Problem

  1. setup staggered orders worker
  2. 1% spread
  3. 0.5% increment

## Specifications

  - Version:0.3.0
  - OS: ubuntu 16.04

Also worth noting that when I setup a worker with 1% spread, 1% increment both assets balances increase where as before this recent update, one of the assets would decrease on this setting so it has improved with recent changes but still not perfect.

First picture is after orders are setup, second is after numerous orders filled. (LTC balance down)

![ltc_btc_1](https://user-images.githubusercontent.com/33036236/40872836-5a051688-664d-11e8-9095-89ae82ffa99c.png)
![ltc_btc_2](https://user-images.githubusercontent.com/33036236/40872843-62c3b360-664d-11e8-9728-642f4d6b07ce.png)

**Comment by MarkoPaasila** [comment]
I wouldn't expect the available balances to increase, because all profits are reinvested and don't show up as available balance. But it is also true that they shouldn't decrease, as excess balance shouldn't be spent at all.

I think this is related to the problems with the logic, which needs some rethinking.

**Comment by CryptoKong** [comment]
oh right i didnt realise re investing profits had been implemented... You can see by the pictures, the BTC balance increases and LTC decreases, perhaps its a case of moving from one side to the other. Anyway... I shall leave it in the hands of the experts :)

**Comment by kokoki1** [comment]
it's the market fee of 0.2% on each completed trade that eat slowly one side of the balance i suspect

**Comment by MarkoPaasila** [comment]
#237 should cover this
