### ISSUE TITLE
GUI Enahancement - Quote and Base Values

### ISSUE THREAD

**Issue by lsji07** [Codaone/DEXBot#186]
## Expected Behavior
GUI should display the total worker quote and base currency in trade currently as well as current values in bot account to assist in quick identification of profitability when working with small tx and values.

Could the % indicator be increased to show the profitability i.e. 1 decimal place to 2,3,4,5,6 etc depending on current bot profit across pair.

## Actual Behavior
No indication of currency on trade orders or values left in bot account on the GUI.

Future Enhancement??

**Comment by lsji07** [comment]
Thought about this some more.

This would massively increase the user awareness of the funds the bot has on trade and in the bot account and time lost in trying to check/get an indication of current bot account values.

Currently to check what the bot's current allocation is to sell/buy's and the bot account is difficult for a average user and this information would help improve the bot's useability especially using the spread method and lots of associated buy/sell positions to track.

**Comment by MarkoPaasila** [comment]
There's pretty much information that could be displayed, and from which the user can draw various conclusions. I think this suggestion needs to be discussed properly, where we decide what information is necessary and why. We want to keep the interface as uncluttered as possible, and if possible, let the user see readily digested information in a form that instantly tells him whether the bot is doing what is supposed to do, and if it is performing well. I will open a separate discussion for that purpose.
