### ISSUE TITLE
GUI freezed when orders are being placed

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#194]
## Expected Behavior
When I start a worker in the gui, I am made aware that it is started and can make other actions in the gui, like scroll, edit another worker, start another worker, etc...

## Actual Behavior
The GUI freezes (displays a hand) for as long as orders are being placed, which in the case of staggered orders, can be tens of minutes.

## Steps to Reproduce the Problem

  1. Create a worker with Staggered Orders
  2. Start worker
  3. Try to do something in the GUI

## Specifications

  - Version: All
  - OS: Xubuntu 16.04

**Comment by MarkoPaasila** [comment]
@mikakoi do I understand correctly that the Qt gui isn't updated as long as another loop is running in the backend? Could you give this some thought with regards to #237 ?

**Comment by mikakoi** [comment]
This is unrelated to #237, it doesn't really fit the scope of it. Fix for this requires rewriting some of the code to use threading where needed

**Comment by bitfag** [comment]
GUI don't freezes now (at least with one worker) because Staggered Strategy now places only 2 orders per maintenance. Old SO placed all orders at once.
