### ISSUE TITLE
Proposal Logo desing contribution

### ISSUE THREAD

**Issue by 0relmely** [Codaone/DEXBot#195]
Hi dear !!

No more preambles attached ideas for logos and environments, with the aim of showing my support to reinforce the corporate image of this magnificent project ...
As you already know @cryptokong I am at your disposal to contribute to the graphic design ...

If you like these ideas, let me know and I will make a publication about UTOPIAN to upload all the related files ...

The whole project is made in vectorail format ...

Your friend Orel

( Please click right mouse button and press view image for more resolution)

![screen](https://user-images.githubusercontent.com/34755801/41174510-a7d02bfc-6b5a-11e8-9a0d-2a9dd291f895.jpg)
![screen2](https://user-images.githubusercontent.com/34755801/41174511-a7fb71d6-6b5a-11e8-994e-62876c4f774b.jpg)
![adscuare black](https://user-images.githubusercontent.com/34755801/41174535-b9c4285e-6b5a-11e8-94e0-65df80f6d67b.jpg)
![adscuare purpple](https://user-images.githubusercontent.com/34755801/41174538-b9edb930-6b5a-11e8-8583-a17e9a1c122e.jpg)
![adblack 02](https://user-images.githubusercontent.com/34755801/41174624-f58ff606-6b5a-11e8-856a-aaf4b52d0807.jpg)
![adpurple 02](https://user-images.githubusercontent.com/34755801/41174625-f5b0f658-6b5a-11e8-873b-7343b3a06520.jpg)
![adblack-03](https://user-images.githubusercontent.com/34755801/41174632-fdb43c66-6b5a-11e8-8846-19531693a71b.jpg)
![adblack-01](https://user-images.githubusercontent.com/34755801/41174633-fdd83ac6-6b5a-11e8-9992-81114268d25e.jpg)
![adblack-02](https://user-images.githubusercontent.com/34755801/41174634-fdfd5c5c-6b5a-11e8-9e9e-25c4d745ca4e.jpg)
![purple-cartel](https://user-images.githubusercontent.com/34755801/41174666-1a0d52f8-6b5b-11e8-88cb-1fcbd5ae5ab9.jpg)
![adpurpple-01](https://user-images.githubusercontent.com/34755801/41174667-1a33f016-6b5b-11e8-9ba1-a2261ff9ba1f.jpg)
![adpurpple-02](https://user-images.githubusercontent.com/34755801/41174668-1a569b34-6b5b-11e8-8b3b-276e3a8db960.jpg)
![black-cartel](https://user-images.githubusercontent.com/34755801/41174669-1a7bbe5a-6b5b-11e8-9d05-17f6b71e7232.jpg)

![cartel negro02](https://user-images.githubusercontent.com/34755801/41174672-1ae80470-6b5b-11e8-8e05-ff1411746a88.jpg)
![key black 01](https://user-images.githubusercontent.com/34755801/41174673-1b144332-6b5b-11e8-8108-1d4ba596ac94.jpg)
![key black 02](https://user-images.githubusercontent.com/34755801/41174674-1b3ca5de-6b5b-11e8-87a9-7c3e09c3098b.jpg)
![key black03](https://user-images.githubusercontent.com/34755801/41174675-1b666860-6b5b-11e8-97df-92ad550a8857.jpg)
![key purple 01](https://user-images.githubusercontent.com/34755801/41174676-1b87eb70-6b5b-11e8-8d75-a81c44aa221e.jpg)
![key purple 02](https://user-images.githubusercontent.com/34755801/41174677-1ba9ae2c-6b5b-11e8-8838-935683989263.jpg)
![key purple 03](https://user-images.githubusercontent.com/34755801/41174678-1bcc4b62-6b5b-11e8-9a7c-d89ec9242000.jpg)
![twitter](https://user-images.githubusercontent.com/34755801/41174691-252fdb56-6b5b-11e8-9b07-18f022a4c06b.jpg)
![icons family](https://user-images.githubusercontent.com/34755801/41174692-2576bb34-6b5b-11e8-95db-1d6032af9804.jpg)
![phone](https://user-images.githubusercontent.com/34755801/41174701-2da2765e-6b5b-11e8-93e2-c22562593f04.jpg)
![logo family](https://user-images.githubusercontent.com/34755801/41174705-31ccc87e-6b5b-11e8-97ca-01af2c0826f2.jpg)

**Comment by MarkoPaasila** [comment]
I think it looks very nice. I would accept the logo and font as such. Do you think they would work without the complex background, or do they require the background to look good? To me it seems like you have designed this as a whole and it looks good as such, but can we cherrypick? I'm asking because it's easier to implement the logo and font than all of everything. Implementing everything would require some work to make sure the interface works with all buttons, information etc...

Personally I tend to like simplistic interfaces, and others like complex. I'm open to discussion. Your design looks really professional. Thanks!

**Comment by 0relmely** [comment]
Hi, thanks for your kind comment!
I'm glad that you like the job, of course you can select what is operative for the moment.

I am open to all the ideas that can be developed, I understand that right now it would be difficult to implement everything ...

I have designed this possible atmosphere with the idea of sharing these banners and ads for twitter, medium, steemit, in short, social networks.

If you look there are two atmospheres one more complex with the circuits and other triangles and colors and the other one is simpler.

I am open to dedicate time to adapt it to where you think appropriate.

For the moment I will make a publication via UTOPIAN to upload all the files in the cloud ...

thanks for this great project

**Comment by MarkoPaasila** [comment]
Excellent! I will discuss this with the developers and cabinet members to see if they agree. If so, we will adopt your designs.

**Comment by thehapax** [comment]
@MarkoPaasila should we close this task?

**Comment by MarkoPaasila** [comment]
I guess so.
