### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by kohako** [Codaone/DEXBot#197]
## Expected Behavior
On install and first start

## Actual Behavior
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://bitshares.openledger.info/ws (2/-1) Retrying in 2 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://bitshares.openledger.info/ws (3/-1) Retrying in 4 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://bitshares.openledger.info/ws (4/-1) Retrying in 6 seconds

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - OS: Mac

**Comment by mikakoi** [comment]
This is a problem in python-bitshares and there is an issue about it here: bitshares/python-bitshares#58

The workaround for this is to remove the file in
`~/.config/dexbot/config.yml`
This will regenerate a config file with a working default node.

**Comment by kohako** [comment]
where is this file found on the mac ?

**Comment by kohako** [comment]
deleted that file. restarted and now get same issue with different node ?
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://status200.bitshares.apasia.tech/ws (2/-1) Retrying in 2 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://status200.bitshares.apasia.tech/ws (3/-1) Retrying in 4 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://status200.bitshares.apasia.tech/ws (4/-1) Retrying in 6 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://status200.bitshares.apasia.tech/ws (5/-1) Retrying in 8 seconds

**Comment by mikakoi** [comment]
That's weird, it's working just fine for me. You can try different nodes by editing the config.yml file and see if that helps with the issue, but the error really isn't something that can be fixed in DEXBot since it comes from python-bitshares.

**Comment by kohako** [comment]
Hi. Im having trouble locating that file again in MAc, what directory does it sit under ?

**Comment by mikakoi** [comment]
I don't have a mac machine at hand right now so I can't check. Can you check the most common places applications save their settings/configs? Try to search for a folder called "dexbot" or a file called "config.yml". I'm also interested where it's saved on mac so if you do find it, please let me know.

**Comment by kohako** [comment]
Hi. I found it and added another node in that is working and still same issue. 
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://bit.btsabc.org/ws (2/-1) Retrying in 2 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://bit.btsabc.org/ws (3/-1) Retrying in 4 seconds

Is there anyone else that can help with the issue? 

To find the folder for the ~/.config/dexbot/config.yml on mac.
1. Open the finder window
2. Click GO in the top menu
3. Hold down the OPTION key and you will notice the LIBRARY folder pops up in the list.
4. Click LIBRARY
5. CLICK APPLICATION SUPPORT folder
6. CLICK DEXBOT folder.

Thanks

**Comment by kohako** [comment]
Any idea how we can get this looked at if it is a python-bitshares issue ?
