### ISSUE TITLE
Build for Raspberry Pi

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#198]
Apparently some dependencies can't be found for Raspberry Pi, and need to be build from source. Could we provide a package?

**Comment by cloud-8** [comment]
Yes this would really help widen the appeal of Dexbot.

**Comment by MarkoPaasila** [comment]
@mikakoi could you comment?

**Comment by MarkoPaasila** [comment]
It's apparently feasible to do make install on raspi if you pre-install python3-pyqt5.10 with apt. So I'll close this.
