### ISSUE TITLE
Unable to delete password settings to re-install

### ISSUE THREAD

**Issue by kohako** [Codaone/DEXBot#205]
## Expected Behavior
Software logs in and starts
## Actual Behavior
Somehow password not working so cant get in. If somehow a password was set is there a way to delete these settings so that a fresh install can be made.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: Windows
  - OS:

**Comment by mikakoi** [comment]
Hey, you can reset your password by removing this file from your system: 'C:\Users\<user>\AppData\Local\Fabian Schuh\bitshares\bitshares.sqlite`

**Comment by THAILAND75** [comment]
hi, i have the same problem - i forgot my password,   didnt find above mentioned file to remove it from my system.  I have reinstalled my office already, but Dexbot again is showing 'unlock wallet' * to put my forgotten password.   How can i unlock it????
thanks
