### ISSUE TITLE
DEXBOT disconnected this morning for a lot of us and haven't been able to reconnect

### ISSUE THREAD

**Issue by hubba1** [Codaone/DEXBot#206]
## Actual Behavior
![error window](https://user-images.githubusercontent.com/20878396/41324195-e8862cca-6e78-11e8-9ea6-13b69f13e7d9.JPG)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - OS: windows 10 64 bit

**Comment by joelvai** [comment]
Edit the config file in `C:\Users\<user>\AppData\Local\codaone\dexbot\config.yml` and set the node to wss://status200.bitshares.apasia.tech/ws

**Comment by MarkoPaasila** [comment]
@joelvai he already seems to have the apasiatech node. By the way the windows terminal is crap :-)

**Comment by mikakoi** [comment]
Yeah it seems like the default node is done, you can manually change it to for example to `wss://bitshares.openledger.info/ws` to fix the issue

**Comment by hubba1** [comment]
ok, where do I add that example?
