### ISSUE TITLE
GUI Freeze on Worker Deletion

### ISSUE THREAD

**Issue by lsji07** [Codaone/DEXBot#213]
## Expected Behavior
Delete worker button, deletes the worker.

## Actual Behavior
On delete the GUI freezes with no error message or status indication. On restart of the gui the worker is back.....note that i am trying to run two workers in one gui or instance but the worker fails to delete.

## Steps to Reproduce the Problem

  1. Create Worker
  2. Delete Worker
  3. Watch gui pause dramatically. I normally wait a few minutes and then kill the process.

## Specifications

  - Version: 0.4.6
  - OS: Win64

**Comment by MarkoPaasila** [comment]
If you delete a worker it cancels all orders, which might take some time (depending on node latency). What strategy did the worker run?

Also how long did you wait after the freeze before killing the bot?

**Comment by lsji07** [comment]
I was running staggered orders. I wait about  5 minutes before killing the process manually. The dex has a better cancel all active orders function I use to clear my bot orders quickly when changing strategies dramatically.

**Comment by MarkoPaasila** [comment]
Yes that's a good workaround for now, as cancelling orders one by one just takes lots of time. There's an issue for batching operations, but it isn't high priority right now.
