### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by joelvai** [Codaone/DEXBot#218]
Documentation needs some updating:
- Installation guide for Windows / Linux / OSX using package and Git
- Commands list and uptick
- File locations (logs)

**Comment by MarkoPaasila** [comment]
Also locations of config files and databases in case the user needs to start from scratch.

**Comment by joelvai** [comment]
I updated file paths for logs, config and databases under "Common problems" tab. OSX is still under work.

**Comment by joelvai** [comment]
I separated Windows and Linux installation guides as their own pages. Updating those further and add a command list for CLI.

**Comment by joelvai** [comment]
Updated Windows and Linux installation guides.

**Comment by joelvai** [comment]
Updated Windows and Linux installation guides.

**Comment by lsji07** [comment]
The new GUI has a toggle switch and no play button as such. Removed reference in the wiki to the play button and inserted toggle switch for now.

**Comment by MarkoPaasila** [comment]
We are still missing a tested procedure for OSX. Let's leave this issue open to bug us until it's done.

**Comment by bitfag** [comment]
Ok, we have wiki page on OSX:
https://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Mac-OS-X-10.12-or-higher
