### ISSUE TITLE
0.4.8 linux gui install error

### ISSUE THREAD

**Issue by developery-nl** [Codaone/DEXBot#220]
I have following error with 0.4.8 linux gui install/excuting (ubuntu 16.04):

[10599] LOADER: Running gui.py
Traceback (most recent call last):
  File "site-packages/graphenelib-0.6.2-py3.6.egg/graphenebase/bip38.py", line 10, in <module>
ModuleNotFoundError: No module named 'Cryptodome'

(Manual install of Cryptodome didnt fix this issue.)

When I replaced the DEXBot-gui file with the older 0.4.6 I have no problems to start the bot.

**Comment by CyberFreedom08** [comment]
could you try this in your terminal : $ pip install pycryptodome

**Comment by grctest** [comment]
I've also had this issue - not been running my bot since the latest release. Isn't the problem that the module is referenced as 'cryptodome' instead of 'pycrpytodome' ? 🤷‍♂️

**Comment by scientistnik** [comment]
I install but nothing change((

**Comment by mikakoi** [comment]
@grctest Can you test the 0.4.6 release and make sure it works for you? I need to figure out what changed after 0.4.6

**Comment by MarkoPaasila** [comment]
@grctest are you doing this on rpi? If so, it might be worth mentioning.
