### ISSUE TITLE
File positions of OSX

### ISSUE THREAD

**Issue by yx2385** [Codaone/DEXBot#221]
DEXBot config: ~/Library/Application Support/dexbot/config.yml
DEXBot log: dexbot.log in the same repository as Makefile

**Comment by MarkoPaasila** [comment]
Thanks! I'll update them to the docs.

**Comment by MarkoPaasila** [comment]
@yx2385  Could you confirm if dexbot.log is in the same folder as Makefile, or if it is in the folder where you run DEXBot (if you used it from the command line)?

Also would you mind searching for the sqlite databases and history file?  "dexbot.sqlite", "bitshares.sqlite", and "history.csv".

**Comment by yx2385** [comment]
dexbot.log is in the folder where you run DEXBot.
dexbot.sqlite and orders.csv are under the same folder as config.yml
bitshares.sqlite is under ~/Library/Application Support/bitshares/

**Comment by MarkoPaasila** [comment]
Thank you! File locations are now updated into documentation.
