### ISSUE TITLE
The fix to assert exception is to re-synchronize your clock on pc 

### ISSUE THREAD

**Issue by ckerflag** [Codaone/DEXBot#222]
OMG I fixed it!!!!!!!   you will never believe what it was....... I have put major labor into fixing my bot I even reset google chrome completely and cleaned everything out and it still was assert exception I hate those words and then today the Dex would not come up and told me to resynchronize  my clock on my pc so I did and man did that ever work good no lag at all soooooo I thought I bet my bot will work now and shazzammm and turned right on and took off and I did a happy dance ......lol  :grinning: :sun_with_face: :man_dancing: :man_dancing:

**Comment by edwinux** [comment]
I have the same issue, on both Linux and Windows, my clocks are synced. Any idea? I spend the whole day on trying to re-install everything, no luck :(

**Comment by ckerflag** [comment]
Not sure why it did not work for you I worked on mine for a week ........I just kept switching nodes and re-syncing the clock using nist.gov and the time.windows one also refreshing and restarting pc.

**Comment by MarkoPaasila** [comment]
I'll add the clock sync to common problems checklist. Thanks!
