### ISSUE TITLE
Relative Orders: Several optional triggers to reset orders

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#226]
For some markets/ circumstances it is better to have relative orders reset after a partial fill like it was originally. If we could have the option to have orders reset after an order is completely filled or partially filled, that would be great.

**Comment by MarkoPaasila** [comment]
Maybe we should define some threshold, like 10% filled, and give the user a checkbox?

**Comment by bitfag** [comment]
I can implement this option. So, do you want a user-defined N% threshold to react on? Or just simple checkbox "Reset orders when partially filled"?

**Comment by MarkoPaasila** [comment]
I think it's better to do with a % if possible, as people will ask for that next if we just do a checkbox.

**Comment by MarkoPaasila** [comment]
I hope we can implement the following reset orders triggers, from which the user can select one or all:
1. Complete fill
2. Partial fill (with % threshold)
3. Time (seconds)
4. Market trade
5. Price change threshold (%. This will be based on the price-source which the user has selected, aka center-price)

Would you consider implementing them all @bitfag ?

**Comment by bitfag** [comment]
Yeah I think it should be possible to implement all of them. Though I'm not sure 4 is really useful because just market trade alone without changed bid/ask will lead to putting the same orders.

**Comment by MarkoPaasila** [comment]
It will surely cause lots of order resets, and often with pretty small changes. But a market trade rarely happens without it changing the market price. I think this option would be more interesting in quiet markets, and an interesting option to have in any case. No strong opinion though.

**Comment by bitfag** [comment]
Ok, I'll start working on these features in next days.

**Comment by bitfag** [comment]
> Time (seconds)

Dexbot currently isn't storing order creation time, so the easiest way to just let user define a custom expiration time. Though it will be not possible to identify all situations when order is not found on the market. Order may disappear because:

* completely filled
* expired
* cancelled manually

I propose to always trigger order reset whether order disappeared for any reason.

P.S. actually it is possible to determine what happened to the order by analyzing account history, but this requires major changes to the dexbot.

**Comment by MarkoPaasila** [comment]
Order expiration time seems like a simple and working idea to me. I think it should be presented as such in the gui: "Order expiration time", and the tooltip could explain that it can be used to reset orders: "Set this lower to force orders reset more often".

**Comment by bitfag** [comment]
@mikakoi  what do you think about switching to UI autogeneration for an existing strategies, for the relative orders for instance? I need to determine a way of adding these new features into GUI.

**Comment by mikakoi** [comment]
Well I don't mind doing that for relative orders, we're not doing anything custom with the UI so it wouldn't break anything. The change would require to modify relative orders controller as some field disabling are done in the ui file.

**Comment by bitfag** [comment]
@MarkoPaasila one more caveat: because order disappearance doesn't mean it was filled, I disabled writing a log entry to the trade log.
