### ISSUE TITLE
Relative orders dynamic spread option

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#230]
We have previously discussed the possibility of adding an option for a worker to place orders at the top of the order book, closest to centre, by a tiny amount say 1 satoshi and if someone places an order above yours, the worker automatically replaces higher. This would be a helpful tool but should come with restrictions such as having to set a maximum or minimum price you wish for the bot to reach. This tool would be very helpful for me in working the Arbitrage Enabling markets. eg: bridge.BTC-open.BTC

Another option we could require is perhaps for the worker to only react to orders of a certain size being above yours.

Any ideas/ suggestions on this would be great.

**Comment by the-scott-davis** [comment]
I agree this has some value, but it should be a checkbox option, and not default behavior.

A lot of times, this type of action can cause dramatic price drops on some of the exchanges, so I definitely agree there should be some configurable options for it so we don't inadvertently suppress our own earnings.

**Comment by MarkoPaasila** [comment]
I actually think that in the end the one-above race-to-zero game is a strategy pretty different from basic relative orders, and could be made as a separate strategy. But other than that, some automation for adjusting the spread would be interesting. The question is; based on what should it be adjusted? Of course the goal would be to get as much volume both ways as possible, at a spread as big as possible. How to find out where the sweet spot lies? Of course narrowing down the spread doesn't necessarily cause more trades to happen - if the market just happens to be quiet. Maybe the goal should be to get a target-portion of all volume happening in the market in question. Like: `if I don't get at least 1% of all volume over the last hour, reduce spread by 1%`

**Comment by CryptoKong** [comment]
Yes i agree this might be better off being its own tool rather than adding to relative orders.

To be honest in a standard market, its not something i personally would use much but for the arbitrage enabling markets it would make a lot of difference. Some of these markets are quite dead and closing the spreads would allow more arb bots to trade. Increasing volumes etc. I think it would be very beneficial to bitshares and all the gateways to tighten the spreads on all these markets.

**Comment by MarkoPaasila** [comment]
Someone will take this kind of strategy into widespread use anyway, and I wonder if it would be best to make it available to everyone or let people do it privately?

**Comment by CryptoKong** [comment]
I think perhaps we should prioritise other things and if we run out of work then consider this strategy. Personally I would like the strategy.

**Comment by joelvai** [comment]
This feature has been implemented, closing this ticket.
