### ISSUE TITLE
Lost connection to node

### ISSUE THREAD

**Issue by freakcoderz** [Codaone/DEXBot#232]
## Expected Behavior
Start Windows GUI

## Actual Behavior
Error connecting during Windows loading window. 

## Steps to Reproduce the Problem

  1. Double click on DEXBot-gui.exe to run
  2. CMD box opens to start process
  3. Get error "Handshake status 502 Bad Gateway
Lost connection to node during rpcexec(): wss://status200.bitshares.apasia.tech/ws (2/-1) Retrying in 2 seconds"

## Specifications

  - Version: 0.4.8
  - OS: Windows 10

**Comment by edwinux** [comment]
same here

**Comment by freakcoderz** [comment]
I switched to an older version and it is connecting fine.

**Comment by lsji07** [comment]
Same as #233. Please close.

**Comment by mikakoi** [comment]
Closed for being a duplicate
