### ISSUE TITLE
Cannot connect bot

### ISSUE THREAD

**Issue by hubba1** [Codaone/DEXBot#233]
## Expected Behavior
connection

## Actual Behavior
![image](https://user-images.githubusercontent.com/20878396/42734457-d917aa2a-8809-11e8-90ea-21344f070fe8.png)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:latest release
  - OS:windows10 64bit

**Comment by edwinux** [comment]
same here

**Comment by lsji07** [comment]
See common problems in Wiki.

Node connection problems
Change the node defined in config.yml. etc etc.

**Comment by hubba1** [comment]
well to the layman that is easier said than done....I know it's easy if you know how

**Comment by MarkoPaasila** [comment]
#236 will fix this
