### ISSUE TITLE
GUI - Not visible with high DPS monitor

### ISSUE THREAD

**Issue by lsji07** [Codaone/DEXBot#235]
## Expected Behavior
GUI display as normal.

## Actual Behavior
High DPS monitors corrupt GUI. 

Issue with windows DPS scaling?

![image](https://user-images.githubusercontent.com/39772657/42758391-3eada7f8-88fb-11e8-9869-59ac70a82419.png)

## Specifications

  - Version: 0.4.8
  - OS: Windows

**Comment by joelvai** [comment]
Is this still problem with the latest release?
