### ISSUE TITLE
Add UI autogeneration for strategies

### ISSUE THREAD

**Issue by mikakoi** [Codaone/DEXBot#243]
The feature will automatically generate a gui file for the edit/add window when a strategy doesn't already have them.
This speeds up creation of new strategies because developers don't need to invest time on gui work. But also allows to create custom gui work for specific strategies.

**Comment by MarkoPaasila** [comment]
Will the easyconfig UI also be able to generate on the fly?

**Comment by mikakoi** [comment]
The plan is that the autogeneration uses the easyconfig parameters to generate the ui
