### ISSUE TITLE
openssl/aes.h no such file cant install

### ISSUE THREAD

**Issue by andresmoya** [Codaone/DEXBot#25]
im getting the following, anyone have any ideas

scrypt-1.2.1/libcperciva/crypto/crypto_aes.c(6): fatal error C1083: Cannot open include file: 'openssl/aes.h': No such file or directory
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

**Comment by MarkoPaasila** [comment]
Let's see if this gets solved once we succeed in creating and executable package for windows.

**Comment by mikakoi** [comment]
Unfortunately this is a problem with the scrypt library that is required by the python-bitshares library. You can read about this more in https://bitbucket.org/mhallin/py-scrypt/issues/18/scrypt-is-not-pip-installable-on-windows but there doesn't seem to be a solution for it currently. Your best option for now is just to wait until we get the windows executable working.
