### ISSUE TITLE
"?" next to data field does nothing

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#252]
The "?" next to the data fields does nothing when I click them or hover over them.

  - Version: 0.5.2
  - OS: ubuntu 16.04

**Comment by lsji07** [comment]
Using windows 64 and on hover I get a brief description of the field.

**Comment by mikakoi** [comment]
I'm also using 16.04 and it works for me. Make sure the window is active when trying to hover.
Also clicking on the question mark makes the tooltip disappear, so make sure not to click it.

**Comment by mikakoi** [comment]
@CryptoKong Was the issue fixed?

**Comment by CryptoKong** [comment]
Hi sorry, i completley forgot to check. I will have a look later and let you know. My apologies.

**Comment by CryptoKong** [comment]
its fine, i was clicking it rather than hovering over. Apologies it took me so long to respond I was on holiday.
