### ISSUE TITLE
Bad gateway - single gateway hard coded in Windows client

### ISSUE THREAD

**Issue by Netzarim** [Codaone/DEXBot#260]
## Expected Behavior
Check multiple gateways

## Actual Behavior
checks one - over and over

## Steps to Reproduce the Problem

  1. start application
  2.see error in python window
  3.

## Specifications

  - Version: 0.5.6
  - OS:Windows 10

Error:
Handshake status 502 Bad Gateway
Lost connection to node during rpcexec(): wss://status200.bitshares.apasia.tech/ws

This site shows the gateways that are live.  Suggest skimming from the page for the link to a valid site.  Also, check other similar pages if this page is dead.

https://status.apasia.tech/?page=1

**Comment by MarkoPaasila** [comment]
@Netzarim how do you know it checks just one node over and over? Is there only one node in your config or can you see it from the error message?

**Comment by MarkoPaasila** [comment]
I'll close this because of no follow-up.
