### ISSUE TITLE
Relative Orders: The strategy trying profit from the spread

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#27]
Make sure to read and understand the [purpose of this software](https://github.com/Codaone/DEXBot/issues/26) before reading this.

This strategy hopes to sell for more than it buys and vice-versa, as much as possible at as much profit as possible. The bigger the difference between buy and sell order the more profit. The more volume the more profit. So far so good.

When the spread is too great very little trading happens. Orders aren't filled and no profit is made.

In order to make any profit according to the strategy, both assets are needed. There needs to be both sell and buy orders. If the price moves enough in one direction, one of the assets can be sold out, and the strategy ceases to function. 

Most of the adjustable parameters of this strategy are for either tuning the spread for maximum profit or coping with price movements for keeping assets somewhat balanced. This strategy must constantly react to changes in market conditions (mainly price), so is mostly suited for a computer constantly online, but can be tuned to better survive some downtime.

So let's define the logic:

# Simplest possible strategy
## Variables
Examples use the MILK:USD market.
**Base Currency:** Unit of account and one of the assets to be traded. (Example: USD)

**Quote Currency:** The "asset of interest" (Example: MILK)

**Center Price:** A price assumed to be the most accurate reference price for a market, reported as _Base Currency_ (Example: 2.25 USD)

**Spread:** The combined distance in percents from center price to lowest own sell order and center price to own highest buy order. It can be assumed that a sensible spread is always less than 20%. (Example: 4.5 %)

**Offset:** An additional variable for helping keep the assets balanced. (Example: 1.115 %)

**Relative Order Size:** [Issue 29](https://github.com/Codaone/DEXBot/issues/29). Portion of asset holdings to use for an order. (Example: 10% of USD, 10% of MILK). Note that this will change the actual order size after every filled order. The bigger the _Relative Order Size_ the more profit, but the less resilience in case of downtime or quick price swings.

## Basic setup
A sell order is placed at `center price + offset + (spread / 2)` with amount `Total MILK * Relative Order Size` 
A buy order is placed at `center price + offset - (spread / 2)` with amount of `Total USD * Relative Order Size`

## Maintenance
It should be assumed that the bot isn't constantly online. Every time the situation is checked and found to have changed, orders are simply cancelled and new ones added according to the strategy. 

# More sophistication to improve performance and tolerance

## Defining Center Price
Of the following mechanisms the bot can use only one at a time, so these alternatives should be represented in the GUI with radio buttons.

### Manual Center Price [DONE]
The user can type in the center price for the strategy to be used. This is suitable for markets where prices are practically stable, like USD:EUR or BitBTC:OPEN.BTC.

### Last Own Filled Order
Use the last filled order of one's own as the center price. This effectively halves the spread from profit making perspective. It also automatically helps balance the portfolio. This is the strategy used at the moment by ihaywood/dexbot.

### External Price Feed
This suits markets where prices are mostly discovered elsewhere, and the prices on BitShares are expected to follow with a small lag. For instance BTC:USD prices on Coinbase are likely to be reflected on BitShares. As a byproduct orders might be filled by the bot, which would reduce liquidity. A "Don't Fill Orders" option is necessary.

### Calculating from Closest Market Orders [DONE]
Excluding own orders. Usually the closest opposite orders are dust orders (insignificant amounts left over from other trades). The center price derived from these orders might or might not represent the _actual_ center price. [Issue 30](https://github.com/Codaone/DEXBot/issues/30)

### Calculating from Market Depth
This bypasses the problem of dust orders. First we figure out at what price we could buy x MILK and at what price we could sell x MILK, then calculate the center price from those prices. This might be more meaningful than the previous method. This method can easily be manipulated in low-participation markets, and a "Don't Fill Orders" option would decrease risk.

### Calculating from Last Opposite Filled Orders
This information is from actual trades. The method should exclude dust trades because they would skew the price too much.

### MPA Price Feeds from the BitShares Blockchain
All Market Pegged Assets and similar algorithmic assets on the BitShares Blockchain rely on price feeds from witnesses (and others). They are automatically averaged into a single "Feed Price", which  can be obtained by the API. This price feed can be used in [SHORT]:[BACK] -markets, where [SHORT]is the MPA and [BACK] is the asset used as collateral.

### Adding (Weighted) Moving Average to any of the Above Methods
This helps filter out noise from signal, but adds some lag to the reaction. It is to be used in combination with one of the above mechanisms. It would be nice to have several different tunable parameters for this method. 

The problem with estimating center price from other orders on the books is that bots will cascade information without knowing where it is derived from in the first place. A Center Price derived from actual filled orders is probably more relevant information.

## Adjusting Spread
In order to find the sweet spot between volume and spread for maximal profit. The user must choose only one of the following methods. Averaging can be used in addition to any one chosen.

### Manual [DONE]
The user sets a percentage manually and adjusts it at will.

### Estimate Current Spread and Beat it
Since the closest orders get filled first, it's worth trying to be there. If several bots do the same, they will compete to close the spread, which is bad for profits but good for the whole. A minimum spread should be given to avoid zero profit

### Estimate Spread from Actual Market Depth
Find out at what price a certain amount can be bought or sold, calculate the spread from that, and decide own spread accordingly. The amount used should be in relation to one's own order sizes. 

### Adding Moving Average to the above
This would help filter out noise, and also avoid constand updating of orders for no real reason. It could  add some additional stability to the market. 

### Relative Order Size [In progress]
If order size is defined as a certain percentage of portfolio, the strategy will automatically resist massive imbalance. A few additional mechanisms can be used to add bias in either direction. 

### Automatically Adjust Offset by Portfolio Balance
Increase offset if we have less MILK than USD, to encourage the market to sell us some MILK rather then buy from us.

### Adding additional staggered orders 
Several orders placed at defined increments further from the Center Price. Order sizes decrease starting from the middle using: `Remaining assets * Relative Order Size`. A good increment is `Spread / 2`. This feature adds resilience in case of sudden price spikes or lengthy off-time.

# Defaults
We might assume that a user leaving the defaults is using a laptop and will check the situation once a day. The best way to prepare for price swings while offline is to add staggered orders from -25% to +33% or something similar. So this should be default.

For the Center Price and the Spead, the default method should be the most robust one implemented, verified by actual tests in real markets.

**Comment by the-scott-davis** [comment]
So, if I understand the strategy correctly, if you have a spread of 1% and place an order on 0.5% on either side of the center price, the relative order bot should only place a new trade once BOTH of those orders complete (unless the center price changes drastically).

However, what I have seen in my use is that once either of the orders is filled, it cancels the other one, and places two new orders.

The problem I see, and correct me if I'm wrong, is that we haven't achieved our spread on this order. Now the bot is placing a new order, which also needs it's spread covered (which never happens). Rinse repeat endlessly. The only way we achieve our spread is if our overall buy/sell costs over hundreds of trades cover the spreads of the individual trades.

Does this seem like a flaw? Should it instead wait until both orders are filled (within reason) to post a new set of trades?

**Comment by MarkoPaasila** [comment]
Nice, first comment :-).

If we wait for both orders to fill before creating new ones, the strategy would likely be stagnant for long times, often months or years. That's not what we want. But you are right in that the problem is real. We need both trades to realize our profit immediately. However, we can also look at average trade prices and amounts and if they are profitable **on average** then the strategy is good.

I am very interested in any ideas on how to make _Relative Orders_ more profitable. Thinking about your concern, maybe a combination of (hopefully) upcoming features could help:
1. Instead of having a filled order trigger order-reset, we could let it be triggered once every x seconds, or once the price moves a certain amount.
2. Moving Average for center price.
3. Calculating center price from a certain depth in the market instead of lowest ask and highest bid.

**Comment by the-scott-davis** [comment]
@MarkoPaasila Yes, I think a change from the center price by a certain percentage would be enough to trigger creating new orders, that's a good idea. Otherwise, if nothing has changed in the market (in the case of no orders for 10 or 15 minutes), why cancel your remaining order, because it could possibly be filled.

**Comment by MarkoPaasila** [comment]
@the-scott-davis in addition to triggering reset by price movement, would a "partial fill", a "single fill", or "both filled" trigger a reset?

**Comment by the-scott-davis** [comment]
@MarkoPaasila 
1. **Partial Fill** I'm not certain on the best course of action for a partial fill. In the case of the partial fill, if the bot is occasionally rechecking the market to see if the center price has changed much, then a a partial fill reset is not needed because the occasional market check would determine a need for a reset.
2. **Single Fill** I think single fill should trigger some recalculation to determine if the center price has changed much (with some assurances, because someone could've just dumped the price with a large sell off for example). So this is a bit of a can of worms. However, I would say if the center point has not changed by more than a certain % variance, then the order should not reset (this will help preserve the other side of your original order and give you a shot at filling it for instance profit). However, if the center price has changed more significantly, then trigger a reset.
3. **Both Filled** should absolutely trigger a reset.

**Comment by lsji07** [comment]
I like the staggered orders concept in relative orders strategy based on the market conditions. Relative orders plus 2 stagger orders, etc. This as a "tickbox" option on relative order strategy would be immensely useful in trialling intervals and spreads used in longer term staggered order strategies. The spread and interval would need to be configurable and as the staggered orders strategy in my opinion.
