### ISSUE TITLE
Relative orders flooding log

### ISSUE THREAD

**Issue by juhanihaapala** [Codaone/DEXBot#270]
## Expected Behavior
Only log things that are meaningful

## Actual Behavior
Relative orders is logging much "INFO - Orders correct on market" 

## Steps to Reproduce the Problem
  1. Start relative orders on any market
  2. Wait for couple minutes 
  3. There comes "INFO - Orders correct on market" to log

**Comment by bitfag** [comment]
Agree, I personally turned this into debug for myself.
