### ISSUE TITLE
Add ability to define custom config path to the GUI

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#278]
For cli version there is a `--configfile` option, would be nice to have a similar option for gui version.

**Comment by MarkoPaasila** [comment]
What's the benefit?

**Comment by bitfag** [comment]
Tuning different configs via GUI. But this can be hard to implement because command-line options parsing with qt app may be tricky.

**Comment by thehapax** [comment]
Agree with bitfag. Would also be nice to able to edit the config.yml file directly from the GUI, especially if i want to use testnet nodes vs mainnet vs my own local.  Either that or the easy way would be just to be a help file inside the GUI that points the user to which file to edit. Right now is a lot of digging through the wiki.

**Comment by joelvai** [comment]
Does current ability to change nodes one by one cover this ticket, or should the capabilities of the node settings still be expanded?

**Comment by bitfag** [comment]
@joelvai the initial idea was to quickly supply different configs to test things.

**Comment by joelvai** [comment]
So I could extend the current solution so that user could pick a file and replace the current list with that, saving the old ones to somewhere or just replace?

**Comment by bitfag** [comment]
@joelvai it is not about just switching nodes, it's about switching the whole configuration. Just a minor feature request.

**Comment by MarkoPaasila** [comment]
Like a whole configuration to test a new/changed strategy with different parameters on the testnet.

**Comment by PermieBTS** [comment]
Remove Label: Requires Discussion

**Comment by bitfag** [comment]
Passing options to a Qt app is not easy. Better to wait core/frontend split, then this will not be needed.
