### ISSUE TITLE
Taker feature

### ISSUE THREAD

**Issue by yusha1439** [Codaone/DEXBot#290]
I have been looking around for any official open source bot to use on Crypto Bridge but so far I have only found dexbot. What I have been trying to figure out though, is a way for dexbot to take orders rather than make. I understand it was intended for market making. What I really need though is a way to execute a one way trade with each time coin is deposited to wallet. Simply put, coin A is deposited to exchange, bot exchanges with market order, we now have coin B. Is there any custom strategy file I can use for this or any hint towards one?

**Comment by the-scott-davis** [comment]
I’d be very careful with that. A few months back some mining pools were doing this exact thing and it suppressed a lot of markets artificially. As such, many bots were banned and in addition to that, the irreparable harm you can do to a coin’s price if this is executed at scale.

**Comment by yusha1439** [comment]
In an active market it doesn't hurt it. Plus, we are not trading on BTC, and it is actually to buy into a coin rather than sell it.

**Comment by MarkoPaasila** [comment]
Our mandate doesn't allow market taking strategies, so I must close this request. But making such a strategy is pretty easy, and can be done into a private/custom dexbot fork by any decent developer. Ask me in pm for suggestons.
