### ISSUE TITLE
Threading or other means of increasing speed.

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#297]
Currently only 10 concurrent workers are allowed, and sometimes even just 2 workers will be enough to render the software unresponsive.

The most limiting aspect of DEXBot technical performance appears to be the single API connection to a BitShares node. If a user has a personal node (localhost, LAN, or broader network), there is no reason to respect that limit. In this case (or if the node in use is not a public node), multiple connections would be allowed. If the bot connects to a public node, only one connection should be allowed.

I opened this issue as a placeholder for discussion about how to best improve the performance (technical) and enable multiple connections and if possible, separate workers each into threads.

I assume #90 and #194 are related to this.

**Comment by MarkoPaasila** [comment]
Would async python-bitshares also speed up the "worker rounds"?

**Comment by bitfag** [comment]
Not exactly. The goal of async processing is that you can run tasks in parallel. While one worker is waiting for response from the node, another worker may do something else. So you basically switching execution from one worker to another in situation when the first worker is waiting for something (I/O).

**Comment by MarkoPaasila** [comment]
But can we separate workers each into it's own thread without async python-bitshares, open several connections, and get a significant speed up?

**Comment by PermieBTS** [comment]
async development is in discussion
