### ISSUE TITLE
Derive Center Price from closest opposite orders - making the center price dynamic.

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#30]
This is almost the simplest way to get a dynamic price for a market. It will work well in already active markets, but in quiet market it can be easily manipulated.

1. Get lowest sell order price (bid). ~Exclude own orders.~
2. Get ~lowest~ highest buy order price (ask). ~Exclude own orders.~
3. Calculate Center Price.

~The bot should keep an eye on the price and reset orders if price has changed more than 1/4 of the spread.~ A filled order can work as a trigger to recalculate _Center Price_.

**Comment by nikolaybaychenko** [comment]
This could be done in a way that the DEXBot provides an option for a user to use automatic center price calculation or not depending on user's preferences. As well as provide with exceptions in cases where a market doesn't have a sell order, buy order or both.

**Comment by nikolaybaychenko** [comment]
It also could be done in a way that user sets a threshold. So it can reset orders when they are out of the threshold.

**Comment by MarkoPaasila** [comment]
Yes it must be optional. Please read [Issue 27](https://github.com/Codaone/DEXBot/issues/27) for a big picture. This specific strategy has three main variables: Center Price, Spread, and Order Size. For each of these, the user will have several mutually exclusive options, which should probably be represented in the GUI with radio buttons. Some of these will have additional variables, which can be presented to the user.

This mechanism for getting the Center Price will be one of many different mechanisms between which the user will have to choose. Now we only have one, manual input, and this will be the second one. The GUI will have to be adjusted for this change.

It's ok to let the user adjust the threshold. We could use 1/4 as default, as I think it's a pretty sane value.

**Comment by MarkoPaasila** [comment]
I'm not sure if the threshold thing belongs to this issue, as this is about getting a center price. Independent of how the user gets the center price, the bot should update orders if the price goes out of threshold. Should I create a separate issue for it?

**Comment by nikolaybaychenko** [comment]
I think the threshold belongs to this issue for the reason you mentioned "bot should update orders if the price goes out of threshold". The threshold will define dynamic center price based on lowest sell order and lowest buy order prices.

**Comment by nikolaybaychenko** [comment]
@MarkoPaasila I think, excluding bot's own orders would be unnecessary because they won't affect on the center price due to the fact that both sell and buy orders placed by the bot have exactly the same spread.

**Comment by MarkoPaasila** [comment]
Scenario:
The market has orders at 0.94 and 1.06 (buy and sell), so the center price is 1.00. The bot places orders at 0.95 and 1.05 (10% spread). Someone cancels the 0.95 order, and the next market order in line is at 0.56. The Center Price according to the other market participants would be 0.81. However the bot disregards market-information and calculates Center Price from it's own orders...
