### ISSUE TITLE
Relative orders: calculate center price from a certain depth in the orderbook

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#300]
Allow users to choose a minimum order size to calculate centre price from. Normally dexbot calculates centre price from nearest buy and sell orders. In less liquid markets other market participants can place small orders to manipulate dexbot users order placements. If an option to ignore orders of a selected size this could help users avoid their workers from being manipulated.

**Comment by MarkoPaasila** [comment]
We are testing this feature in the new strategybase. Once it works I think we can port it to Relative Orders.

**Comment by MarkoPaasila** [comment]
Once this is done in strategybase, it could be ported back into Relative Orders.
