### ISSUE TITLE
[Windows] RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by matricea** [Codaone/DEXBot#309]
## Expected Behavior

Program to run as designed.
## Actual Behavior
Error in on_market: 'for_sale'
Traceback (most recent call last):
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitsharesapi\websocket.py", line 276, in on_message
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitsharesapi\websocket.py", line 276, in <listcomp>
  File "lib\site-packages\events-0.3-py3.5.egg\events\events.py", line 95, in __call__
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitshares\notify.py", line 144, in process_market
  File "lib\site-packages\bitshares-0.1.14-py3.5.egg\bitshares\price.py", line 487, in __init__
KeyError: 'for_sale'

## Steps to Reproduce the Problem

  1. Start DexBot program
  2. Start 2 workers, one by one
  3. After a short while or right after workers are started, the error appear.

## Specifications

  - Version:
  - OS: Windows 10 Pro

**Comment by joelvai** [comment]
Does the market have sell orders in it?

**Comment by matricea** [comment]
yes, 4,1 btc on bids and 446 ltc on ask

**Comment by joelvai** [comment]
What strategy are you using?

**Comment by matricea** [comment]
Amount:15%
Center price auto
Spread 1.25%
After I added the 3rd worker it crashes right after starting the workers.
Removing first worker it crash:
"[1268] LOADER: Running pyi_rth_qt5.py
[1268] LOADER: Running gui.py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "dexbot\worker.py", line 162, in run
  File "dexbot\worker.py", line 52, in init_workers
RuntimeError: dictionary changed size during iteration"

Could be my Windows. I'll try from another one.
I'll be back with updates.

**Comment by MarkoPaasila** [comment]
@matricea any progress?

**Comment by matricea** [comment]
Yes,
Tried on 2 Windows 10 computers.
It seems that the only way when the bot is stable on my computers is to have only 1 running worker.
I'll give a try on Linux also

**Comment by MarkoPaasila** [comment]
@matricea are they all using Relative Orders?

**Comment by matricea** [comment]
yes, tested on random percentages.
Also, spread, same kind of tests, from 0.1% till 300%
Another thing, at some point, when the bot is hanging, some of the open orders are not cancelled,

**Comment by MarkoPaasila** [comment]
Did you have an account per worker, or did you somehow manage to use one for many workers? Just making sure.

**Comment by matricea** [comment]
yes, one account per worker.
I would love to have more workers under same account ;)

**Comment by MarkoPaasila** [comment]
This seems related to the issue where Relative Orders cancels orders of other workers.

**Comment by bitfag** [comment]
I'm experiencing time-to-time hangs, they are caused by interrupted communication with the node. For some reason pybitshares doesn't handling such situations, maybe because they are lower-level than pybitshares, maybe somewhere inside websocket libraries. Hard to debug because the exact way to reproduce is unknown.

**Comment by bitfag** [comment]
Ok, the originally described issue is different from what I described in previous comment. I'd rather open a new issue for this. Original issue is something unique and windows-specific, and no one other reported it.

@matricea any news? Did you managed to run dexbot on windows?

**Comment by bitfag** [comment]
The error "RuntimeError: dictionary changed size during iteration" looks like the same dict() object was modified from another thread while it was used somewhere else. Since no one reported similar problem I wonder what exact actions sequence of @matricea did to get that error. Maybe there is a way to reproduce?

**Comment by bitfag** [comment]
Ok I removing this from sprint because we didn't get any additional data. Let's wait until someone reproduce this.
