### ISSUE TITLE
How should I add this trading robot to the clone chain of other bts?

### ISSUE THREAD

**Issue by jindiaoke** [Codaone/DEXBot#316]
There are a lot of decentralized exchanges that have been developed to replicate bts graphene. How can I use this trading robot for other decentralized exchanges?

**Comment by MarkoPaasila** [comment]
Its somewhere in python-bitshares, where chain-id's are stored. In addition you probably have to specify a node from that network. I would probably ask those clone projects to clone dexbot too and customize it to their networks.
