### ISSUE TITLE
Allow any Asset as Base

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#32]
One of the most interesting features of the BitShares DEX is the possibility to trade directly between any two assets. Demand for such markets will likely increase in the future. Once Market Makers can easily bootstrap any market, the possibility might even be exposed in the reference client. Remittance is one example where users might have the need to exchange from some smartcoin to another, where neither is one of the current "base" assets. Another example is a cryptocurrency enthusiast who wants to profit from the fluctuation between two promising coins without circulating over BTC or USD. 

DEXBot should also allow the Market Maker to provide liquidity in any market.

**Comment by mikakoi** [comment]
This already a feature, closing this.
