### ISSUE TITLE
Python error?

### ISSUE THREAD

**Issue by wizardofwhere** [Codaone/DEXBot#328]
## Expected Behavior
Working my way through Linux install instructions when I type in "make install-user" the installation fails

## Actual Behavior
I see the following error

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-78x1kc4q/pyinstaller/
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: 19 Tara
  - OS: Linux mint

**Comment by MarkoPaasila** [comment]
We need the last 10 lines from the error message. They contain the essential information.

**Comment by wizardofwhere** [comment]
wizardofwhere@wizardofwhere-desktop:~/dexbot$ make install-user
python3 -m pip install --user -r requirements.txt
Collecting pyqt5==5.10 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ae/4b/c7315ba7a266d493ee50c4597b1b4dea2348896a49115b5192b21adf1a47/PyQt5-5.10-5.10.0-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl
Collecting pyqt-distutils==0.7.3 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7a/58/458679654c85a70894c60bd7fcf02c3c75548f16f6659300df4632aac6be/pyqt_distutils-0.7.3-py2.py3-none-any.whl
Collecting pyinstaller==3.3.1 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/3c/86/909a8c35c5471919b3854c01f43843d9b5aed0e9948b63e560010f7f3429/PyInstaller-3.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u85ndkbe/pyinstaller/

**Comment by mikakoi** [comment]
Your python installation seems to be missing setuptools module, you can manually install the module from here https://pypi.org/project/setuptools/

**Comment by MarkoPaasila** [comment]
@wizardofwhere I think you can install with `sudo pip install setuptools` or `pip install --user setuptools`. Please let us know if it works so we can close this issue.

**Comment by wizardofwhere** [comment]
I did that already as I'm researching the issue with my vast 5 days of Linux experience.  Anyhow the issue is still there
wizardofwhere@wizardofwhere-desktop:~/dexbot$ make install-user
python3 -m pip install --user -r requirements.txt
Collecting pyqt5==5.10 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ae/4b/c7315ba7a266d493ee50c4597b1b4dea2348896a49115b5192b21adf1a47/PyQt5-5.10-5.10.0-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl
Collecting pyqt-distutils==0.7.3 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7a/58/458679654c85a70894c60bd7fcf02c3c75548f16f6659300df4632aac6be/pyqt_distutils-0.7.3-py2.py3-none-any.whl
Collecting pyinstaller==3.3.1 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/3c/86/909a8c35c5471919b3854c01f43843d9b5aed0e9948b63e560010f7f3429/PyInstaller-3.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-71facipr/pyinstaller/
Makefile:22: recipe for target 'pip-user' failed
make: *** [pip-user] Error 1
wizardofwhere@wizardofwhere-desktop:~/dexbot$ ^C
wizardofwhere@wizardofwhere-desktop:~/dexbot$

**Comment by MarkoPaasila** [comment]
Have you googled the error?

**Comment by wizardofwhere** [comment]
Yep I've been trying to google my way forward as best I can nothing yet though

wizardofwhere@wizardofwhere-desktop:~/dexbot$ pip freeze
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
wizardofwhere@wizardofwhere-desktop:~/dexbot$

**Comment by MarkoPaasila** [comment]
I'll close this issue, as we can't support each platform out there, and this doesn't seem to occur on ubuntu.
