### ISSUE TITLE
Test python-bitshares 0.2.0

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#335]
It has breaking changes, described [here](https://github.com/bitshares/python-bitshares/blob/release/0.2.0/RELEASE_NOTES.md) To benefit from future improvements we must likely make the necessary changes to DEXBot.

**Comment by MarkoPaasila** [comment]
Some issues reported already by @vvk: https://github.com/bitshares/python-bitshares/issues/149

**Comment by joelvai** [comment]
I tested with websocket version 0.48.0 and while testing, didn't run into any problems.
