### ISSUE TITLE
Improve status texts in Staggered Orders

### ISSUE THREAD

**Issue by joelvai** [Codaone/DEXBot#338]
Worker leaves "Placing a xxx order for x.xxx @ x.xxx" as last status message giving a impression that the bot has crashed. Another case is when worker has placed all the orders and it is restarted, it will show "Starting worker" even though it has already started.

This could be improved by informing user that the worker is still running, but not currently doing anything after placing all the orders. Showing "Worker is running" for example while there is nothing happening.

**Comment by bitfag** [comment]
Probably we can add a solution similar to Relative Orders to show correct messages in the GUI and simultaneously do not spam the log.

**Comment by bitfag** [comment]
The problem is worker log messages and GUI messages are different things. Log messages are for activity logging, while GUI messages should indicate status of the worker. Maybe it's good idea to split them.

**Comment by MarkoPaasila** [comment]
Ages ago I suggested a dot for each worker that indicates the status: green for "active and everything ok", yellow for problem and red for disabled.

**Comment by bitfag** [comment]
This should be resolved after #582 (split core and frontends) as there will be an API to query worker status.
