### ISSUE TITLE
Cannot start worker: issues on worker start

### ISSUE THREAD

**Issue by cloud-8** [Codaone/DEXBot#342]
## Expected Behavior

Worker starts, provides status text of current process and begins strategy. 

## Actual Behavior

Workers do not start and no orders are placed. CLI and GUI provide little information on issue. Main response on windows is error: `Connection is already closed` and linux 'Errno 32: Broken Pipe`
Dexbot 0.71 tested on Linux Mint (ubuntu) 18.04, Windows 10 64 and Raspbian Stretch June 2018. I suspect this is something to do with websocket connection. 

Linux: 
![linuxmint dexbot](https://user-images.githubusercontent.com/12015961/46718484-e47b0780-cc9d-11e8-8c41-0b25f7b58cab.jpeg)

Win10 64:
![dexbot win10 64](https://user-images.githubusercontent.com/12015961/46718496-f0ff6000-cc9d-11e8-80e4-ace9bc1a8c72.jpeg)

New fresh install of 0.71. All nodes setup. Tried setting to known working public node with 100ms ping and same behaviour. No issues with local internet connection is solid. Both CLI and GUI exhibit same behaviour of workers not functioning. 

## Steps to Reproduce the Problem

  1. Install Dexbot for Linux or Windows as per instruction guide. 
  2. Create staggered orders worker in GUI and save details
  3. Turn worker on

## Specifications

  - Version: 0.71
  - OS: Linux Mint (ubuntu 18.04), Windows 10 64 bit, Raspbian Stretch Hune 2018.

**Comment by MarkoPaasila** [comment]
Change the node to a better one. See [wiki](https://github.com/Codaone/DEXBot/wiki/Common-problems#node-connection-problems)

**Comment by cloud-8** [comment]
Lowest latency node is 93ms which was tried in addition to top 5 nodes with lowest ping. Deleted all other nodes from settings on GUI view in win and restarted. Same behaviour

**Comment by cloud-8** [comment]
On Linux after connection fail there is also `Error ontick()` `Market history plugin is not enabled`

**Comment by MarkoPaasila** [comment]
Sorry, I thought you were someone new.
Can you check your websocket-client version with `pip freeze`

**Comment by cloud-8** [comment]
@MarkoPaasila `websocket-client==0.53.0`

**Comment by joelvai** [comment]
Downgrade websocker-client to version 0.48.0, that should fix the problem.

**Comment by MarkoPaasila** [comment]
Shouldn't the installation take care of that?
```
install_requires = [
    'bitshares==0.1.22',
    'uptick>=0.1.9',
    'click',
    'sqlalchemy',
    'ruamel.yaml>=0.15.37',
    'sdnotify',
    'appdirs>=1.4.3',
    'pycryptodomex==3.6.4',
    'websocket-client==0.48.0'
]
```

**Comment by cloud-8** [comment]
Downgraded to 0.48.0 and same results

**Comment by joelvai** [comment]
Have you tried of running the Windows version from the executable with a node that works for sure?

**Comment by MarkoPaasila** [comment]
I'm sure he has. He runs a public node :-)

**Comment by cloud-8** [comment]
Yep, using a list of about 10 known working nodes and have even used only our own public node and deleted all the others.

**Comment by cloud-8** [comment]
@MarkoPaasila same issue in virtual env. See below
![img_2133](https://user-images.githubusercontent.com/12015961/46855762-2db28f00-ce37-11e8-8532-c67ee46e6e42.JPG)

**Comment by MarkoPaasila** [comment]
I'll try with a fresh Mint VM if I find the time.

**Comment by joelvai** [comment]
@cloud-8 did you manage to solve the connection issue?

**Comment by cloud-8** [comment]
@joelvai issue not solved. Same problems with latest dexbot release too 0.79

**Comment by joelvai** [comment]
Just to narrow down all the options, do you have any firewall, antivirus or VPN in use that could block the connection.

**Comment by cloud-8** [comment]
@joelvai no firewall or VPN, tried in two separate locations on 3 separate systems (win, linux, rPI).

**Comment by joelvai** [comment]
I haven't been able to reproduce this problem with 0.7.9 using Linux or Windows 10. Can you provide me the following things
- Python dependencies `pip freeze`
- Nodes that you are using

**Comment by MarkoPaasila** [comment]
@joelvai he's the guy we are talking with on Slack

**Comment by bitfag** [comment]
This seems like just a local connection issue, not a dexbot-wide issue. @cloud-8 if you still experiencing any problems, please join our telegram group https://t.me/DEXBOTbts and we will try to investigate your issue.
