### ISSUE TITLE
Upgrade from 5.17 to 7.1 workers can not be started

### ISSUE THREAD

**Issue by Wall-ETcoin** [Codaone/DEXBot#343]
## Expected Behavior
When starting the existing worker that is older then 0.5.17 version.
It should start normally and say "Done initializing Staggered Orders".
And start the worker properly.

## Actual Behavior
Once the new app v.0.7.1 is started it displays the old workers, but when clicked on "Turn Worker on"
it gives error and does not want to start the worker.
pin to node 640ms

Have the following errors:
Traceback (most recent call last):
File "dexbot\worker.py", line 76, in init_workers
File "dexbot\strategies\staggered_orders.py", line 90, in __init__
KeyError: 'mode'

## Steps to Reproduce the Problem

  1. Create worker with client older then 0.5.17 and start it, so it works and places orders
  2. Start 0.7.1
  3. Turn worker on

## Specifications

  - Version: 0.7.1
  - OS: Windows 7

**Comment by MarkoPaasila** [comment]
Staggered orders changed between 0.5.17 and 0.7.1, and the old config doesn't work with the new. Try deleting the worker and creating a new one. Either using the gui or editing the file by hand.

**Comment by Wall-ETcoin** [comment]
Is it possible to convert the worker, as I would like not to cancel any placed orders?

**Comment by joelvai** [comment]
You can try manually patch the worker config to match this, mode should be the only new field in the config.

> - account: 
    - center_price: 0.0
    - center_price_dynamic: true
    - fee_asset: BTS
    - increment: 1.00
    - instant_fill: false
    - lower_bound: 10.0
    - market: 
    - mode: mountain
    - module: dexbot.strategies.staggered_orders
    - spread: 2.00
    - upper_bound: 100.0

**Comment by Wall-ETcoin** [comment]
thx for the idea, but I have noticed in the new conf there is no 

> - amount:

>

**Comment by joelvai** [comment]
You can leave it out. Staggered Orders does not use it anymore, since it will allocate all available funds.

**Comment by MarkoPaasila** [comment]
I guess this is solved, so I'll close.
