### ISSUE TITLE
get_order_cancellation_fee() and get_order_creation_fee() should use Core Exchange Rate

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#351]
Now they are use convert_asset() function which uses market ticker latest() price to convert. This is incorrect for fee calculation because fees uses Core Exchange Rate not market price.

**Comment by MarkoPaasila** [comment]
Yes CER should be used. It doesn't need to be refreshed every 3s, so whoever makes the fix could see if it could be made to refresh once every 24h

**Comment by bitfag** [comment]
I think CER lookup may be performed once per worker run and store the reply into variable, and use it later like cache.
