### ISSUE TITLE
cli setup for Staggered Orders shows Relative Orders options.

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#353]
## Expected Behavior
The configuration dialog shows only settings related to Staggered Orders

## Actual Behavior
"Market depth" or something similar is apparently shown

## Steps to Reproduce the Problem

  1. `dexbot-cli configure`
  2. Select "staggered orders" strategy
  3. Continue until you see unrelated options.

## Specifications

  - Version: 0.7.8
  - OS: Linux

**Comment by racheta09** [comment]
i was actually editing a relative order and converting it into staggered when i faced the issue

**Comment by joelvai** [comment]
I tested on DEXBot version 0.7.9 converting a Relative Orders worker to be a Staggered Orders worker, and didn't run into this issue. Were you able to reproduce this every time?

**Comment by racheta09** [comment]
i tried recreating it on my local pc with latest from git and the issue wasn't recreated but the worker wasn't changed to staggered order

**Comment by joelvai** [comment]
Thank you for more details, I will look more into this.

**Comment by joelvai** [comment]
I managed to confirm this bug, it actually does change the worker to staggered orders but keeps the relative order's parameters saved in the configure file as well.
