### ISSUE TITLE
Test with up to date dependencies (pypi) and include what works

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#354]
To be done when not feeling like doing anything demanding.

**Comment by joelvai** [comment]
Pybitshares 0.2.0 updates many of the out dated dependencies but some are still intact. These are some of the dependencies that could be updated later:

- [ ] 1. PyInstaller 3.3.1 => 3.4
- [ ] 2. PyQT 5.10 => 5.11.3
- [ ] 3. cryptography 2.3 => 2.3.1
- [ ] 4. pycryptodomex 3.6.4 => 3.6.6

**Comment by MarkoPaasila** [comment]
I'm testing with all those packages and stuff seems to work. Got one new error, but will see if it repeats.

**Comment by joelvai** [comment]
Can you post the error if it reoccurs?

**Comment by MarkoPaasila** [comment]
Of course

**Comment by thehapax** [comment]
is this issue still open? or shall we close it?
