### ISSUE TITLE
Add ability to set loglevel in GUI

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#355]
User running a bot in GUI mode should have an ability to set logging mode. Default log level is "info", sometimes I need "debug" log from an user to do a troubleshooting. Now I'm forcing a user to run via cli for that.

**Comment by MarkoPaasila** [comment]
Would it be a command line argument when launching dexbot-gui?

**Comment by bitfag** [comment]
Probably better to use settings in the GUI because passing cli args to qt app may be painful, and also GUI setting is more user-friendly.

**Comment by bitfag** [comment]
Windows users often reporting bugs but we are not able to ask debug log, not good.

**Comment by bitfag** [comment]
Should be resolved via #582
