### ISSUE TITLE
Only 5 workers allowed

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#359]
## Expected Behavior
10 workers allowed

## Actual Behavior
After 5 workers the "add worker" is disabled

## Steps to Reproduce the Problem

  1. Make 5 workers

## Specifications

  - Version: 0.7.9 zip
  - OS: Windows

Reported by "Nick" on Telegram

**Comment by joelvai** [comment]
Found the bug. Check that keeps count of the workers adds double the amount thus set limit of 10 is actually half.

**Comment by NickDavison** [comment]
Was previously able to add 10 workers. Bot crashed after running for a while and only 5 workers were configured on restart ( workers 1-5 remained).

I am now unable to add additional workers.

**Comment by NickDavison** [comment]
> Found the bug. Check that keeps count of the workers adds double the amount thus set limit of 10 is actually half.

Wow that was quick Joelvai ;)

**Comment by joelvai** [comment]
I fixed the bug and it will be on the next release.
