### ISSUE TITLE
Show a notice popup in the GUI when the bot has an error

### ISSUE THREAD

**Issue by mikakoi** [Codaone/DEXBot#36]
Currently the bot only quietly disables itself and doesn't let the user know that an error has occurred in the GUI version.
The GUI should use the notice dialog to notify the user of all the log.critical errors.

**Comment by MarkoPaasila** [comment]
An orange blinking dot? This would be visually nice, combined with an eventual green dot that blinks on any activity.

**Comment by ihaywood3** [comment]
currently working on dialogs. Won;t do coloured dots at this stage
