### ISSUE TITLE
Changing relative order size on Workers throws error

### ISSUE THREAD

**Issue by NickDavison** [Codaone/DEXBot#364]
## Expected Behavior

Orders are replaced with new order that reflect the relative order size percentage

## Actual Behavior

Traceback (most recent call last):
  File "dexbot\views\errors.py", line 95, in func_wrapper
  File "dexbot\views\worker_item.py", line 175, in handle_edit_worker
  File "dexbot\views\worker_item.py", line 153, in reload_widget
  File "dexbot\views\worker_item.py", line 47, in setup_ui_data
  File "dexbot\views\worker_item.py", line 108, in set_worker_profit
TypeError: float() argument must be a string or a number, not 'dict'

Also get error pertaining to attempting to sell 0, looks like the new percentage propagates before the old orders are cleared?

## Steps to Reproduce the Problem

  1. Create worker on relative spread
  2. Trade
  3. Change Relative Order Size

## Specifications

  - Version: 0.79
  - OS: Windows 10 Pro

**Comment by MarkoPaasila** [comment]
@joelvai can you check the code to see how it calculates orders sizes when relative order size is changed, and how it calculates order sizes in any case? I had a quick glimpse, and it looked like the logic lacks something, or then I just missed it. The order size should be related to the total amount of the asset (just in case some of it is allocated in orders at the time of calculating).

**Comment by joelvai** [comment]
@MarkoPaasila I tested with relative order size of 50%. It allocates exactly that amount of QUOTE to sell and BASE to buy. Changing the size to 60% cancels orders correctly and creates new orders with correct sizes.

**Comment by joelvai** [comment]
@NickDavison did you use one account to run only one worker and with what worker parameters? I haven't been able to reproduce this bug.

**Comment by bitfag** [comment]
@joelvai look at the exception, the error seems related to updating GUI profit stider and not order size at all. Editing worker just triggered widget reload etc.

**Comment by joelvai** [comment]
@bitfag I know, but what I am looking with this is that maybe this is caused only when there are no available funds for the other asset or something else.

**Comment by bitfag** [comment]
@NickDavison "attempting to sell 0" is an another error which is probably not fixed yet, and was reported as #276 which I'll try to fix a bit later.

Regarding  original error `TypeError: float() argument must be a string or a number, not 'dict'`, please try the latest version of dexbot and feel free to reopen the issue if you'll get that again.
