### ISSUE TITLE
price.py, TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by NickDavison** [Codaone/DEXBot#367]
## Expected Behavior

Worker Places buy and sell orders

## Actual Behavior

Worker does nothing then throws the following error when disabled / re-enabled

Traceback (most recent call last):
  File "dexbot\worker.py", line 142, in on_market
  File "site-packages\events-0.3-py3.5.egg\events\events.py", line 95, in __call__
  File "dexbot\strategies\relative_orders.py", line 342, in check_orders
  File "dexbot\strategies\base.py", line 1269, in get_order
  File "site-packages\bitshares-0.1.22-py3.5.egg\bitshares\price.py", line 446, in __init__
TypeError: 'NoneType' object is not subscriptable

## Steps to Reproduce the Problem

  1. Enable Worker
  2. Disable Worker that is not functioning
  3. Re-enable Worker

## Specifications

  - Version: 0.7.9
  - OS: Windows 10 Pro

**Comment by joelvai** [comment]
Can you provide the config for the worker that caused this.

**Comment by bitfag** [comment]
Very strange case. Example code to emit such error:

```python
def foo():
    return None

foo()[0]
```
`>>> TypeError: 'NoneType' object is not subscriptable`

But in price.py we have the function call which returns just empty list when querying unexistent object: 

```python
bitshares.rpc.get_objects(['1.3.01'])
```
`>>> [None]`

Which doesn't result in TypeError:
`[None][0]`
`>>>`

**Comment by bitfag** [comment]
Ok, since we don't know how to reproduce this bug, I've added a logging of order_id in case of Exception. This will help to catch this in the future.
