### ISSUE TITLE
Only One Worker Initiates on Staggered Order Mode

### ISSUE THREAD

**Issue by NickDavison** [Codaone/DEXBot#369]
## Expected Behavior

All workers initiate, then manage orders on their relative exchange

## Actual Behavior

One order initiates, other workers hang on "starting worker"

## Steps to Reproduce the Problem

  1. Create 5 workers, set to staggered / mountain
  2. Start all workers
  3. Possibly Multithreading Issue?

## Specifications

  - Version: 0.7.9
  - OS: Windows 10, I3-4130

**Comment by NickDavison** [comment]
It sounds like that is the case, I set the upper bounds crazy high, I will try reducing the bounds a little.

**Comment by MarkoPaasila** [comment]
@NickDavison with some 5% increments and +-100x boundaries (1 000 000%) range it makes some 200 - 300 orders, which takes some time to place. However it should take turns between workers. I don't know if it just takes that much time to estimate all order sizes with a +10 000x range and 0.1% increments. It all happens on one thread, including the GUI. You might be able to get more insight by using cli (which of course isn't provided for windows).

**Comment by NickDavison** [comment]
@MarkoPaasila,

That seems to be exactly what is going on, is multi-thread support on the feature list?

**Comment by joelvai** [comment]
It is still under discussion since it would require quite a bit re factoring.

**Comment by joelvai** [comment]
@NickDavison did Marko's answer solve your problem?

**Comment by MarkoPaasila** [comment]
I didn't actually provide any solutions :-)

**Comment by PermieBTS** [comment]
@joelvai whats the status of this issue?

**Comment by MarkoPaasila** [comment]
One solution is threads and/or async, and the other is batching order placements.

**Comment by thehapax** [comment]
@PermieBTS also assigning to permie as this is an epic issue

**Comment by PermieBTS** [comment]
@MarkoPaasila why mightn't this be an issue on cli? 

Is it the problem of the bot taking ages to do all the calculations and cycle through placing the inital orders?

Does the same time-lag problem exist once SO orders are placed? (In the long term running after intial setup)
Staggered orders itself is generally a slow placed strategy. 

Async would make a big difference, but only for the time-senstive strategies. How far would async improve the amount of workers that can be run simultaneously? 
There is no limit on cli workers currently

Does the 3second block time factor in at all to how fast the bot can place orders?

Would it be correct to say that the status of this issue can only be on hold until such time async development is considered?

**Comment by bitfag** [comment]
@PermieBTS PyQT (GUI) is async, it has event loop inside. The rest of the dexbot is synchronous. It means when the program execution switching from GUI to any worker, GUI execution is on hold, it just waits until worker will finish current task and return.

Async and/or multithreading allows parallel execution of all dexbot subtasks.

With cli, there is no a GUI which can freeze. So, workers are just being called one-by one in infinity loop.

3 second block time is not matter. Order placing limiting factor is CPU only because you need some cycles to sign a transaction.

**Comment by PermieBTS** [comment]
async development is in discussion.

Closing this issue
