### ISSUE TITLE
MAC OS failure to execute

### ISSUE THREAD

**Issue by Bluffet** [Codaone/DEXBot#379]
## Expected Behavior

Expected to be like windows
## Actual Behavior

Terminal launches and gets to this point:

[12629] Error loading Python lib '/var/folders/f8/kdsmx9x88xj0c2006s6_c7980000gn/T/_MEI1m52B5/Python': dlopen: dlopen(/var/folders/f8/kdsmx9x88xj0c2006s6_c7980000gn/T/_MEI1m52B5/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/f8/kdsmx9x88xj0c2006s6_c7980000gn/T/_MEI1m52B5/Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/f8/kdsmx9x88xj0c2006s6_c7980000gn/T/_MEI1m52B5/Python

Then stops

## Specifications

  - Version: all the versions of DexBot I have tried, including the latest 3
  - OS: Mac OS 10.9.5

**Comment by MarkoPaasila** [comment]
Did you install from source or download the package?

**Comment by thehapax** [comment]
I confirm Dexbot version 0.7.19 is working on OSX 10.13.6 for the downloadable executable. the releases should work for 10.12 on up. 

the error from the end user is for Symbol not found: _clock_getres, which is not implemented for OSX versions below 10.12 .  So unfortunately we are not supporting the OSX version 10.9.5 at this point in time. Please upgrade your OSX accordingly to use Dexbot. @MarkoPaasila @joelvai @Bluffet 

Suggested action is to close this bug report.

**Comment by Bluffet** [comment]
Then it should be stated somewhere that it's not possible. It was the executionable, @MarkoPaaasila
