### ISSUE TITLE
Cannot create a worker that was created before but now was deleted

### ISSUE THREAD

**Issue by Cobb-Chang** [Codaone/DEXBot#380]
## Expected Behavior
creat a worker that i deleted but it was there before. 
when i want to save a that worker, it report error

## Actual Behavior
Traceback (most recent call last):
  File "/home/cobb/dexbot/dexbot/views/errors.py", line 95, in func_wrapper
    return func(*args, **kwargs)
  File "/home/cobb/dexbot/dexbot/controllers/worker_controller.py", line 244, in handle_save
    self.add_private_key(private_key)
  File "/home/cobb/dexbot/dexbot/controllers/worker_controller.py", line 59, in add_private_key
    wallet.addPrivateKey(private_key)
  File "/usr/local/lib/python3.6/dist-packages/bitshares-0.2.1-py3.6.egg/bitshares/wallet.py", line 162, in addPrivateKey
    raise KeyAlreadyInStoreException("Key already in the store")
bitshares.exceptions.KeyAlreadyInStoreException: Key already in the store

## Specifications

  - Version:0.7.19
  - OS:ubuntu 16.04

**Comment by joelvai** [comment]
The private key for the account is already stored. If you are trying to create a worker with an account that you previously used in another worker but deleted, the key is already stored.

**Comment by Cobb-Chang** [comment]
> The private key for the account is already stored. If you are trying to create a worker with an account that you previously used in another worker but deleted, the key is already stored.

alread deleted the old worker

**Comment by joelvai** [comment]
![image](https://user-images.githubusercontent.com/10694041/47841863-a2884180-ddc3-11e8-9b49-6110dbbf989f.png)
Try leaving the `Private Active Key` blank.

**Comment by Cobb-Chang** [comment]
the "wallet.py" is different between below two version. so i used the old version to solve this problem

bitshares version:0.2.1
def addPrivateKey(self, wif):
        """ Add a private key to the wallet database
        """
        try:
            pub = format(PrivateKey(str(wif)).pubkey, self.prefix)
        except:
            raise InvalidWifError("Invalid Key format!")
        #if str(pub) in self.store:
        #    raise KeyAlreadyInStoreException("Key already in the store")
        self.store.add(str(wif), str(pub))


bitshare verision:0.1.19
def addPrivateKey(self, wif):
        """ Add a private key to the wallet database
        """
        pub = self._get_pub_from_wif(wif)

        if self.keyStorage:
            # Test if wallet exists
            if not self.created():
                raise NoWalletException
            self.keyStorage.add(self.encrypt_wif(wif), pub)

**Comment by Cobb-Chang** [comment]
> ![image](https://user-images.githubusercontent.com/10694041/47841863-a2884180-ddc3-11e8-9b49-6110dbbf989f.png)
> Try leaving the `Private Active Key` blank.

it's a good method. it's ok now

**Comment by joelvai** [comment]
@Cobb-Chang I leave this open, I will make changes to properly handle the error.
