### ISSUE TITLE
Implement orders depth limit for Staggered Orders

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#386]
When Staggered Orders strategy is used with huge depth and big orders count, it causes long maintenance time and lots of orders replacements especially when we are adding new funds from outside.

To improve strategy speed, decrease overhead and maintenance time, I propose to limit orders count by N depth (user-defined parameter).

I would like to work on this.

**Comment by MarkoPaasila** [comment]
I don't want to say "don't do it". It doesn't sound like a massive job, so just do it. Would it worth checking first that it doesn't unnecessarily sort and iterate over the whole list every time or something else heavy? If not, then leaving further orders unplaced seems necessary.

**Comment by bitfag** [comment]
Well, it's actually possible to avoid loading of all own orders in some cases which may speed up initial orders placement and "silent" maintenance when nothing happening.

Though keeping N orders seems best to me because maintaining far-from-center orders is useless waste of own resources and blockchain nodes resources. While trading is happening around center, we are continuously replacing far orders to allocate profits. Settings adjustment like changing spread/increments also requires replacing of all orders. We actually interesting on maintaining only "operational depth" orders, which is vary depending on worker online %. The less worker is online, the more depth it needs, and vice versa.

**Comment by MarkoPaasila** [comment]
"Operational Depth" is a good term :-)
