### ISSUE TITLE
timed reset of orders

### ISSUE THREAD

**Issue by phobos777** [Codaone/DEXBot#388]
for inactive markets, it would be nice to reset the time of orders,  i.e. every 15 minutes, reset the orders around a new dynamic center price.  and/ or reset the market every 15 minutes with a 6% spread instead of a 7% spread.  so a sliding functions according to time.

**Comment by MarkoPaasila** [comment]
You already can have orders reset at any interval in seconds. Is that what you mean, or something else?
There's also dynamic spread, so that your spread is x% of the market spread at the time of resetting orders.

**Comment by PermieBTS** [comment]
> You already can have orders reset at any interval in seconds

Closing this issue
