### ISSUE TITLE
Add DEXbot docs to dev.bitshares.works

### ISSUE THREAD

**Issue by Agorise** [Codaone/DEXBot#396]
In the Bitshares docs, there is a section for creating your own coin, connecting your exchange, integration etc, but running the best dexbot on the planet is not included. 
https://dev.bitshares.works/en/master/index.html 
 
Could you guys add your swagger ui or other dexbot docs to the main works site too? 
 
Link it also so that it never goes out of date from the master?

**Comment by MarkoPaasila** [comment]
I think this would better be done after we hand over the project to the community - that is, in January.

**Comment by PermieBTS** [comment]
I'll try and get this done this week

**Comment by PermieBTS** [comment]
BBF have no plans to add outside projects.
Issue closed
