### ISSUE TITLE
uptick install is broken on dexbot install; missing dependency (setup.py)

### ISSUE THREAD

**Issue by thehapax** [Codaone/DEXBot#431]
for digital ocean (DO) droplet:  18.10 ubuntu default install.  Uptick doesn't install at this moment from `pip3 install uptick` had to go to manual install. 

https://uptick.readthedocs.io/en/latest/installation.html

**Comment by thehapax** [comment]
Same issue for 18.04 LTS as 18.10 with uptick 

Tabulate is missing on uptick install in either setup.py or requirements.txt

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by MarkoPaasila** [comment]
My last installation missed tabulate and ccxt. This was on a Raspberry Pi with Arch Linux ARM.

**Comment by bitfag** [comment]
Confirming missing tabulate.

ccxt is installed.
