### ISSUE TITLE
Staggered Orders: 99.99% order filled, leaves dust and doesnt replace order on other side

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#432]
On staggered orders, I keep getting orders filled that leave a tiny dust order still in place. Rather than replacing the 99.99% filled order on the other side the worker waits for the dust order to be filled.

When this happens the worker should cancel the remaining dust order and replace the filled balance on the other side.

Below is a screen shot showing the remaining dust order (0.01BTS) after 99.99% fill and the unplaced balance (204BTS), both are circled.

![image](https://user-images.githubusercontent.com/33036236/51136883-79f5dc80-1835-11e9-926b-20aa78413d9c.png)

## Specifications

  - Version:0.7.9
  - OS:ubuntu 16.04

**Comment by CryptoKong** [comment]
this issue can be closed i just realised im on an ages old version, whoops!

**Comment by bitfag** [comment]
Why close? This is still actual for the current version. Fixing this will require some refactor of the logic. Need some thinking and experimenting  on how to handle this best way.

**Comment by CryptoKong** [comment]
Apologies. Probably should have let my workers run a bit to see what happened on latest version first, ive not had any orders filled yet. Re opened.

**Comment by bitfag** [comment]
FYI, I implemented a solution for that, currently testing locally now.

**Comment by thehapax** [comment]
ok assigning to @bitfag
