### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#433]
I think we need to build and maintain official docker image for the project. Docker image is an easy and unified way to try the software and deploy onto VPS.

**Comment by thehapax** [comment]
agreed. sending a link to permie since i don't know what his github username is

**Comment by thehapax** [comment]
Ok I will discuss with Permie and then see if we can get this task assigned to you @g3d @PermieBTS

**Comment by thehapax** [comment]
@PermieBTS can we get @g3d added as a contributor?

**Comment by g3d** [comment]
@PermieBTS why closed?

**Comment by PermieBTS** [comment]
My understanding from gabriel was the docker was sufficient.
Apologies, ive re-opened

**Comment by bitfag** [comment]
As users have issues installing dexbot (#565), and we do not have automatic installation test which tests the [HOWTO](https://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Ubuntu-Linux), I want to pay attention to this issue. What I want to do:

* Refactor Dockerfile from #439 (already done locally)
* Enable automatic build of docker image using Travis CI
* Enable automatic deploy of docker images onto Docker Hub for `master` and `devel` branches

**Comment by bitfag** [comment]
#439 merged.
