### ISSUE TITLE
Multiple workers on same accounts with assets intersections

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#434]
User can create multiple workers one the same account for example for BTC:LTC and USD:BTS pairs. That's fine.

Another situation may be BTC:LTC and BTC:ETH markets. There is BTC asset intersection. Dexbot doesn't handle well such situations now. Solutions:
* (staggered) refuse to create such workers and complain
* (relative) refuse and complain
* Make Relative orders probably tolerate this assets intersections. Should not be a big deal
* Theoretically it's possible to support multiple staggered workers on same account with assets intersection. Dexbot will need to treat intersected asset balance as "common" and divide it across workers evenly or according to specified % (config option). The thing which requires attention here is how to handle adding more workers. Rebalance intersected asset across workers or just assume user should add more funds to supply new worker.

As that feature is specific, probably we need to poll the community to understand the demand for it. That feature may be really wanted as crypto-bridge introduces market-making program which designed to work with single account.

**Comment by bitfag** [comment]
There is a one logical problem for Staggered Orders strategy. Logically correct would be split balance across workers on the beginning (initial orders placement), and then maintain them similarly as it would be different accounts. What I mean: if you have a worker with 50% of balance and then some orders was filled, it's share % in common balance should also decrease proportionally to amounts of filled orders, for example down to 40%. So basically if worker will get all orders filled, its share in common balance should be 0 and it must not eat additional balance designated for another workers.

Such logic would require:
- Adding some state into the SO strategy to track initial center price
- Some refactoring of the strategy

Adding state will hurt an ability to run the strategy from different machines with same config.

**Comment by thehapax** [comment]
@bitfag I marked this as a feature and assigned to you. What is the current status?

**Comment by bitfag** [comment]
@thehapax the feature was implemented and I got positive feedback from Cryptobridge, probably I'll PR this soon when we will fully resume.

**Comment by daveydd** [comment]
I really like this feature? Now I have to create several account in CB and serveral workers to get this done. With the feature I don't need those extra CB accounts anymore.

**Comment by bitfag** [comment]
@PermieBTS it's not yet merged anywhere, I'll reopen.

**Comment by bitfag** [comment]
TODO: prevent workers with same account and same market.

**Comment by bitfag** [comment]
> TODO: prevent workers with same account and same market.

* in cli configure full config isn't passed to `configure_worker()` so it cannot validate against other workers
* Maybe it's good idea to add a check into ConfigValidator, but #631 needs to be addressed
