### ISSUE TITLE
Staggered Orders performance estimation 30d instead of 7d

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#435]
Staggered Orders is a long term strategy. It is often the case that price moves in only one direction for 7 days, and thus there would be no profit within that time span.  Increasing the measurement span to 30 days would increase the probability of one or more reversals, enabling the indicator to reveal the "profit".

**Comment by bitfag** [comment]
I'd rather refactor the whole profit tracking algo. Realized and Unrealized Profit/Loss and so on.
