### ISSUE TITLE
SO: keep virtual orders state across restart

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#442]
Currently virtual orders are being reconstructed from scratch on each restart. This creates the following issues:

* If working mode changed & dexbot restarted, virtual orders will be restored according to a new mode. When switching from valley mode to mountain or neutral, this will create available funds which will be reallocated into closer-to-center orders.
* If orders size increase round is in progress, increase smoothness will be distorted

Solution: save virtual orders into state, and restore them on startup. Determine how to better store virtual orders. As a state, dexbot sqlite db may be used, or json serialized dump file, or something other. Determine what is best.

**Comment by MarkoPaasila** [comment]
This is important. If operational depth is max, then the orders themselves contain all necessary information, but if we only place orders to some depth, then it is necessary to remember state. Otherwise we make losses.

**Comment by PermieBTS** [comment]
> If working mode changed & dexbot restarted, virtual orders will be restored according to a new mode. When switching from valley mode to mountain or neutral, this will create available funds which will be reallocated into closer-to-center orders.

Restarting DEXBot after a strategy mode change may be a common "mistake" users make so I think during the refactor a way to store orders across restart should be developed. 
This is a kind of polishing of the user experience as well. 
DEXBot should be easy to configure (if you know what you're doing with market making) and the possibility that the user harms their strategy accidentally should be prevented.
