### ISSUE TITLE
SO: prevent moving liquidity away from center by increase logic

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#444]
In valley and neutral modes we have increase rounds staring from closest to center order. In conjunction with orders limiting logic it naturally causes moving liquidity from orders around center to further orders.

With center price fluctuations in small range this may looks like this (valley mode, order amounts in BASE on buy side and in QUOTE for sell side):

```
80 80 80 100 100 100 60 50 40 30 <center> 20 30 40 50 50 50 100 100 100 80 80
```

The problem is that closer-to-center orders will not be increased until further order (80) will not be increased (80 -> 100).

I suggest to modify increase logic in the following manner (buy side example):

```
80 80 80 100 100 100 60 50 40 40
80 80 80 100 100 100 60 50 50 50
80 80 80 100 100 100 60 60 60 60
80 80 80 100 100 100 70 60 60 60
80 80 80 100 100 100 70 70 60 60
80 80 80 100 100 100 70 70 70 60
80 80 80 100 100 100 70 70 70 70
80 80 80 100 100 100 90 70 70 70
80 80 80 100 100 100 90 90 70 70
80 80 80 100 100 100 90 90 90 70
80 80 80 100 100 100 90 90 90 90
80 80 80 100 100 100 100 90 90 90
...
80 80 80 100 100 100 100 100 100 100
80 80 100 100 100 100 100 100 100 100
80 100 100 100 100 100 100 100 100 100
100 100 100 100 100 100 100 100 100 100
```

Note that this proposed solution will not disturb correct transition from mountain to valley mode:

```
10 20 30 40 50
20 20 30 40 50
20 30 30 40 50
30 30 30 40 50
30 30 40 40 50
30 40 40 40 50
40 40 40 40 50
...
```

This change is especially actual in conjunction with #443

**Comment by thehapax** [comment]
@bitfag do you want to own the three SO tasks? if so, let me know. how many hours estimate each?

**Comment by thehapax** [comment]
assigning to @bitfag

**Comment by bitfag** [comment]
@thehapax yeah, I already implemented described changes and now I'm testing them in production. Overall took 8h. They are not explicit bugfixes bug enhancements, so we can postpone them for later iterations (not include into bugfix sprint).

**Comment by thehapax** [comment]
@PermieBTS see bitfag's comment

**Comment by MarkoPaasila** [comment]
Valley mode should always try to maximize order size as far as possible. It should start from the very furthest order and increase that if it can. If not, then the second furthest.

**Comment by bitfag** [comment]
@MarkoPaasila it's still very different from mountain mode. The goal is to mitigate consequences of order size limiting which happens when price moves back and forth filling only 1-2 orders deep. E.g. prevent turning valley into deeper valley.

Notice that furthest orders will be increased first if order is less than `closest order + 1 increment`. Let's assume 1 increment is 10%:

10 10 10 100 100 100 60 50 40 40  <---- here is 10/40 difference is bigger than 10%
10 10 **20** 100 100 100 60 50 40 40
10 **20** 20 100 100 100 60 50 40 40
...
50 50 50 100 100 100 60 50 40 40 <----- furthest orders are now bigger than closest 40
50 50 50 100 100 100 60 50 **50** 40
50 50 50 100 100 100 60 50 50 **50**
50 50 **60** 100 100 100 60 50 50 50 <---- continue to increase further orders
**60 60 60** 100 100 100 60 50 50 50
60 60 60 100 100 100 60 **60** 50 50 <--- again increase closest and so on
