### ISSUE TITLE
UI Add description to the wallet password create - Users confused

### ISSUE THREAD

**Issue by PermieBTS** [Codaone/DEXBot#448]
Lots of users are confused by the local wallet created by DEXBot to encrypt their active keys.
Adding a small text explaination would help alot

**Comment by MarkoPaasila** [comment]
"A password for encrypting the file that contains your private keys"

**Comment by thehapax** [comment]
User should be made aware that this wallet is part of uptick, run with dexbot locally and not the cloud or bin wallet on bitshares dex.

**Comment by thehapax** [comment]
uptick and its password is also not uninstalled by default when dexbot it uninstalled/reinstalled

**Comment by thehapax** [comment]
@PermieBTS i'm adding a message to the cli configure on initial setup for wallet password create.
