### ISSUE TITLE
SO: disallow spread == increment

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#450]
We have a check `if self.target_spread < self.increment:` which must ensure `spread > increment`, but it allows `spread == increment` which is a no-no. Need to correct the check.

**Comment by MarkoPaasila** [comment]
Should we ensure spread is at least increment + market fee + some extra? Assuming market fee is 0.2% both ways, and there's the order creation cost, spread should be at least increment + 0.5%.

**Comment by bitfag** [comment]
Good point, market fee should be taken into account.

Limit order create fee is matter only if order amounts are low. On huge orders even spread of `increment + 0.01%` may cover blockchain fees.

**Comment by bitfag** [comment]
Thnx @MarkoPaasila, just discovered #453 looking into market fee. :rofl:

**Comment by bitfag** [comment]
@MarkoPaasila ok, I added a proper check now which takes market fees into account.

**Comment by PermieBTS** [comment]
@bitfag what is the status of this issue?

**Comment by bitfag** [comment]
@PermieBTS  See above, merged into devel https://github.com/Codaone/DEXBot/pull/452
