### ISSUE TITLE
get_market_fee() returns wrong fee

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#453]
`get_market_fee()` in base.py returns market fee of `self.fee_asset`. It is surprising how we missed it. It is not we need at all, market fee is fee paid for buying some asset. E.g. the function must take "asset" as argument and return market fee for that asset (not self.fee_asset).

Because of wrong market fee, `get_market_xxx_price()` also returns slightly distorted values.

**Comment by MarkoPaasila** [comment]
So currently `get_market_fee()` get's the market fee for the defined fee asset, not the quote or base? Yes that's wrong. But the order creation fee still needs to use fee asset, so make sure not to mess that up

**Comment by bitfag** [comment]
Sure, for this there is a separate method `get_order_creation_fee()` which doesn't use `get_market_fee()`.

**Comment by bitfag** [comment]
Ok I think `get_market_fee()` is just redundant method because it just references an asset property. Fee info getting is as simple as calling `self.market['quote'].market_fee_percent`
