### ISSUE TITLE
Reconfigure/remove cli configure

### ISSUE THREAD

**Issue by PermieBTS** [Codaone/DEXBot#458]
Cli config is clunky and could be removed.

Document the parameters and give examples.

**Comment by thehapax** [comment]
I am investigating refactor cost and itemizing to-do items.

**Comment by thehapax** [comment]
@PermieBTS just to be clear I am still working on this issue and it is the bulk of my time rightnow

**Comment by thehapax** [comment]
closing as in next merge.
