### ISSUE TITLE
Implement auto-adding discovered strategies into GUI

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#461]
Currently to add a strategy into GUI it is required to edit dexbot/controllers/worker_controller.py and add a new strategy into `strategies()`. Without this the strategy will not appear in the GUI.

Solution: implement discovery mechanism to auto-add strategies into GUI. Strategies must hold some attribute saying "I'm a GUI-ready strategy, add me", otherwise they are cli-only.

**Comment by thehapax** [comment]
@PermieBTS epic issue

**Comment by PermieBTS** [comment]
This would tie in to a "custom strategy" feature wouldnt it?
Where the user could write a private strategy and add it to their own personal isntance of DEXBot 

Big project.
Review in 1 month

**Comment by MarkoPaasila** [comment]
Did anyone review IanHaywoods pull request for strategy sideloading using pip/pypi?

**Comment by bitfag** [comment]
Ok I reviewed that commit 99e2b1431f46133e5b4e584564c4381d24da965b
Looks like auto-discovered strategies are added into cli/GUI automatically. I didn't used that possibility so just didn't aware it's even exists.
