### ISSUE TITLE
ZeroDivisionError in update_gui_profit()

### ISSUE THREAD

**Issue by Soggydan** [Codaone/DEXBot#462]
## Expected Behavior
initialise worker and complete buy and sell order then continue to run

## Actual Behavior
stops after buy order placed with this error

## Steps to Reproduce the Problem

  1. use large orders
  2. different coin
  3.

## Specifications

  - Version: 
  - OS:  windows 10
![image](https://user-images.githubusercontent.com/47578440/52671520-33b69a80-2f13-11e9-956d-5f286061de3c.png)
![capture](https://user-images.githubusercontent.com/47578440/52671564-50eb6900-2f13-11e9-90d8-015521d9f043.JPG)

**Comment by thehapax** [comment]
linked issue to #438

**Comment by bitfag** [comment]
No it's not related to #438.
