### ISSUE TITLE
Can the order-replacement delay interval be customised in the GUI?

### ISSUE THREAD

**Issue by RobJah** [Codaone/DEXBot#466]
Beloved Dexbot Devs,

When a worker makes some big gains it cancels orders n replaces m with bigger ones. This is in principle a fantastic thing, but can really keep my workers busy right when the action is happening and the worker should be focussed on just maintaining its orderbooks.

Can this mechanism for instance be made to run on a 30min interval, or be accessible as a function in the gui?

I'd prefer it to run on an pre-set interval to keep the gui from getting more and more complicated. 

Thanks for ur time

**Comment by bitfag** [comment]
In Staggered Orders, maintaining spread has higher priority over allocating profits. It means if an order around center was filled, opposite-side order will be placed **before** allocating profits.

When the worker has nothing to do, it raises check interval up to 120 seconds. This is why it may react to filled orders with a delay. Meanwhile, other workers can be busy allocating profits.

**Comment by RobJah** [comment]
Sounds good. When I look at the clients in which i run 10 workers, this really is an issue. Sure the worker itself might not instantly start allocating, but because i have multiple BTS-market-workers those are all active within the same 15 or 30 min. Therefore they cockblock eachother. Could the interval be hightened? Or could the interval be personalized by making it accesible through the gui?

**Comment by bitfag** [comment]
Min/max check intervals are hardcoded in the code to 3 and 120 seconds respectively. Adjusting these intervals may help, but real problem is that dexbot overall slow because it is synchronous (everything executed step-by-step and not in parallel). As a solution I already proposed refactor the whole dexbot with async support.

Related to #297 #369

**Comment by MarkoPaasila** [comment]
@RobJah it's not clear that replacing orders faster increases profits. In fact I have observed the very opposite. I'm not capable of quantifying the effect, so I can't suggest any intelligent logic to benefit from the phenomenon.

**Comment by RobJah** [comment]
Im not saying anything is more profitable for you but for me it is a problem that when 2 workers are allocating profits, and another one gets a lot of action, that the replacing of those filled orders is going less fast. 

But, I am pleased with bitfag's last reply and hope his suggestion on speeding things up delivers.

**Comment by CryptoKong** [comment]
Async should speed up order replacements once implemented?

**Comment by bitfag** [comment]
Basically it will allow one worker to work while another worker is waiting IO. Running worker now spending time to IO waiting while blocking all other workers.

**Comment by thehapax** [comment]
@RobJah @CryptoKong  can we rename to something more descriptive of the issue instead of `@CryptoKong make me post this?`

**Comment by PermieBTS** [comment]
Issue should be solved once DEXBot is async.

Closing this issue
