### ISSUE TITLE
cli.py configure "market" setting is confusing

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#470]
```
Market - BitShares market to operate on, in the format ASSET:OTHERASSET, for example "USD:BTS" [USD:BTS]
```

Market offered as BASE:QUOTE while it actually QUOTE:BASE

**Comment by thehapax** [comment]
editing text to be seen as  BitShares market to operate on, in the format "QUOTE/BASE, for example "BTS/USD" [BTS/USD]" . let me know if that is OK.

**Comment by thehapax** [comment]
also - "Manual center price - In an immature market, give a center price manually to begin with. BASE/QUOTE [0.00000000]: " 

should this be represented as QUOTE/BASE ? or leave as BASE/QUOTE?

**Comment by bitfag** [comment]
Price should be in BASE/QUOTE.
