### ISSUE TITLE
cli.py configure uses : as market separator

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#471]
```
Market - BitShares market to operate on, in the format ASSET:OTHERASSET, for example "USD:BTS" [USD:BTS]
```

Using ":" will lead to further errors because in some places in the code only "/" accepted as a separator.

**Comment by thehapax** [comment]
making pull request

**Comment by thehapax** [comment]
@PermieBTS I vote we are consistent across the board and drop the ":" and use "/" as a separator.

**Comment by PermieBTS** [comment]
@thehapax I agree

**Comment by bitfag** [comment]
Was fixed.
