### ISSUE TITLE
"Worker is disabled" log flooding

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#474]
Currently events are passed to disabled workers resulting in log flooding with "Worker is disabled" message.

Instead, I propose to emit this at "error" loglevel and only once (don't pass events to disabled workers).

**Comment by manikey123** [comment]
claiming the issue @thehapax @PermieBTS @bitfag

**Comment by PermieBTS** [comment]
Hello @manikey123 
Are you in the DEXBot Telegram?
t.me/DEXBotbts

**Comment by bitfag** [comment]
@PermieBTS I would like to fix it as this bug annoys me.

**Comment by PermieBTS** [comment]
Okay go ahead

**Comment by joelvai** [comment]
PR #533 closes this issue.
