### ISSUE TITLE
Move DEXBot.log file to the install folder

### ISSUE THREAD

**Issue by PermieBTS** [Codaone/DEXBot#490]
## Expected Behavior
DEXBot.log file is in the install folder

## Actual Behavior
DEXBot.log file is currently created in the folder in which dexbot command is run

## Steps to Reproduce the Problem
Ensure dexbot.log in created inside the install folder upon installation
  1.
  2.
  3.

## Specifications

  - Version:
  - OS:

**Comment by bitfag** [comment]
I investigated this a bit and found some controversy:

* cli version logs into 'dexbot.log' in current directory
* gui version logs into user_data_dir/dexbot.log, where user_data_dir is ~/.local/share/dexbot on linux

It's logical to have the same location for both version, though it will mess the things if user running several dexbot instances simultaneously (I personally use this)

**Comment by gabev** [comment]
...second that !

**Comment by PermieBTS** [comment]
Go ahead vvk

**Comment by bitfag** [comment]
This change breaks system-wide installation, report from telegram:

> BTW, I also found that the newly-released bot tries to create a log file in /usr/bin/dexbot.log, which caused a permission error.

> I used the sudo pip3 install -e .  command as per the guide for rasberry pi (https://github.com/Codaone/DEXBot/wiki/Setup-guide-for-Raspberry-Pi)

**Comment by MarkoPaasila** [comment]
`user_data_dir/dexbot.log` seems like the correct place. Another option is working directory, but the former would be more consistent.
