### ISSUE TITLE
Staggered Orders Unit Test

### ISSUE THREAD

**Issue by thehapax** [Codaone/DEXBot#517]

**Comment by bitfag** [comment]
Testing plan:

SO strategy is complex and contains lots of logic. Unittests can cover only part of the strategy. To test overall strategy logic it requires to have integration tests (tests which checks multiple components at a time). I'm not sure which is proper approach: to do individual unittests first, or start right from integration tests.

Methods which requires integration testing:

* maintain_strategy
* allocate_asset
* increase_order_sizes
* tick

Methods could be covered with unittests (fully or partially):

* log_maintenance_time
* calculate_min_amounts
* calculate_asset_thresholds
* refresh_balances
* refresh_orders
* remove_outside_orders
* restore_virtual_orders
* replace_real_order_with_virtual
* replace_virtual_order_with_real
* store_profit_estimation_data
* check_partial_fill
* replace_partially_filled_order
* place_closer_order
* place_further_order
* place_highest_sell_order
* place_lowest_buy_order
* calc_buy_orders_count
* calc_sell_orders_count
* check_min_order_size
* place_virtual_buy_order
* place_virtual_sell_order
* cancel_orders_wrapper

**Comment by bitfag** [comment]
SO tests has been implemented.
