### ISSUE TITLE
Relative Orders Unit Test

### ISSUE THREAD

**Issue by thehapax** [Codaone/DEXBot#518]
Assigned to bitProfessor

**Comment by bitProfessor** [comment]
done

**Comment by thehapax** [comment]
> done

@bitProfessor can you please make a pull request? thanks

**Comment by bitProfessor** [comment]
Ok
On 04/08/2019 14:15, octomatic wrote:

done

@bitProfessor can you please make a pull request? thanks

**Comment by bitfag** [comment]
@bitProfessor what is the status of RO tests?

**Comment by bitProfessor** [comment]
@thehapax @bitfag 
http://htmlpreview.github.io/?https://github.com/bitProfessor/DEXBot/blob/mytest/report.html
 `bitshares_engine.get_own_buy_orders:: filter_buy_orders() ` This method can not be found. Is it not timely for me to update it?

**Comment by bitProfessor** [comment]
> @bitProfessor what is the status of RO tests?

I'm back, very close to finish.

**Comment by bitProfessor** [comment]
@thehapax  filter_buy_orders() Is inherited from BitsharesPriceFeed,but ,Strategy of RO don't work.

**Comment by bitfag** [comment]
@bitProfessor please prepare the tests in separate branch so I could review / modify them and then fix bugs in RO.

**Comment by bitProfessor** [comment]
Ok




| |
bitprofessor
邮箱：bitprofessor@163.com
|

Signature is customized by Netease Mail Master

On 08/28/2019 16:04, Vladimir Kamarzin wrote:

@bitProfessor please prepare the tests in separate branch so I could review / modify them and then fix bugs in RO.

**Comment by bitProfessor** [comment]
hi @bitfag, I'd like to push on your branch first, so you can check it first, OK?

**Comment by bitfag** [comment]
Hmm I have a local branch with work in progress, no need to use it, just use current `devel` as base branch to put tests on.

**Comment by bitProfessor** [comment]
Ok


On 09/05/2019 16:28, Vladimir Kamarzin wrote:

Hmm I have a local branch with work in progress, no need to use it, just use current devel as base branch to put tests on.

**Comment by bitfag** [comment]
RO tests has been merged.
