### ISSUE TITLE
KOTH Unit Test.

### ISSUE THREAD

**Issue by thehapax** [Codaone/DEXBot#519]

**Comment by thehapax** [comment]
todo after base strategy refactoring

**Comment by bitProfessor** [comment]
ok

**Comment by bitProfessor** [comment]
hi @bitfag 。No refactoring koth?

http://htmlpreview.github.io/?https://github.com/bitProfessor/DEXBot/blob/dev/tests/strategies/kh_report.html

**Comment by bitfag** [comment]
Yes, KOTH is not up-to-date with `devel`.

**Comment by bitProfessor** [comment]
hi @bitfag 
http://htmlpreview.github.io/?https://github.com/bitProfessor/DEXBot/blob/mytest/tests/strategies/king_of_the_hill/hk_uninittests_report.html

1.` add self.buy_price=None @line 95`
2. `add self.sell_price=None @line 96`
3. 183 line: `own_orders_ids = [order['id'] for order in self.get_own_orders]`==>>`self.get_own_orders()`
4.  line 249 , Event 'is_too_small_amounts' is not declared

**Comment by bitfag** [comment]
@bitProfessor can you please prepare the tests on top of my branch `454-1-sat-bot-strategy` so I could merge it locally and apply fixes?

**Comment by bitProfessor** [comment]
@bitfag ok

**Comment by bitfag** [comment]
Tests was integrated & strategy released.
