### ISSUE TITLE
Staggered orders error: cant calculate centre price when fixed centre price is given

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#563]
## Expected Behavior
worker should work off given fixed centre price

## Actual Behavior
error says cant calculate centre price

## Steps to Reproduce the Problem

  1.setup staggered worker in completley dead market with no orders (i was using valley mode)
  2.start worker
  3.error

## Specifications

  - Version:0.10.1
  - OS:ubuntu 18.04

**Comment by bitfag** [comment]
@CryptoKong I was unable to reproduce this issue, can you please copy-paste your dexbot config here?

**Comment by CryptoKong** [comment]
Sorry not sure which file you mean, could you be more specific, in the mean time, here is my setup and the error message. 
![image](https://user-images.githubusercontent.com/33036236/56475045-d4c55280-647a-11e9-942a-446a4e63dffb.png)

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.6/site-packages/dexbot-0.10.1-py3.6.egg/dexbot/worker.py", line 76, in init_workers
    view=self.view
  File "/home/cryptokong/.local/lib/python3.6/site-packages/dexbot-0.10.1-py3.6.egg/dexbot/strategies/staggered_orders.py", line 115, in __init__
    self.update_gui_profit()
  File "/home/cryptokong/.local/lib/python3.6/site-packages/dexbot-0.10.1-py3.6.egg/dexbot/strategies/base.py", line 1390, in update_gui_profit
    profit = self.calc_profit()
  File "/home/cryptokong/.local/lib/python3.6/site-packages/dexbot-0.10.1-py3.6.egg/dexbot/strategies/base.py", line 1167, in calc_profit
    max_quantity_base = base_balance + quote_balance * center_price
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

![image](https://user-images.githubusercontent.com/33036236/56475058-ffafa680-647a-11e9-8319-dbf58c46dd59.png)

**Comment by bitfag** [comment]
You got this traceback from the console?
Dexbot config is usually `~/.config/dexbot/config.yml`

**Comment by bitfag** [comment]
The error `TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'` is a different error, I created a new issue for it, #567

**Comment by bitfag** [comment]
@CryptoKong I was able to reproduce this issue, no further input is needed, thanks.

**Comment by CryptoKong** [comment]
Ok cool, sorry for my slow response, busy bank holiday weekend here. Glad you could reproduce. Cheers
