### ISSUE TITLE
Missing config.yml from windows zip package

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#57]
I don't know how relevant Win 7 is, but in any case here's the error:
![image](https://user-images.githubusercontent.com/6001014/38296991-c2274cfc-37fb-11e8-8176-eb1f3ae85bcc.png)

I downloaded 1.0.6 zip, extracted it and executed with both double click and from powershell.

**Comment by mikakoi** [comment]
config.yml was moved outside the package a while back, closing this.
