### ISSUE TITLE
Upgrade version of python-bitshares to 0.3.x

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#570]
Need to perform version upgrade, as it contains bug fixes and some of our new features will depend on this new version.

**Comment by joelvai** [comment]
I agree. I suppose this could be next on the list after the base refactor is done and before actually new features are implemented. Its not the biggest job, but requires mostly testing.

**Comment by PermieBTS** [comment]
@joelvai I agree

**Comment by bitfag** [comment]
I would like to do this before base refactor, as #551 depends on this.

**Comment by PermieBTS** [comment]
Is this 570 necessary for https://github.com/Codaone/DEXBot/issues/515 ?

**Comment by bitfag** [comment]
@PermieBTS yes

**Comment by thehapax** [comment]
my concern about this upgrade to 0.3.x is that currently i'm refactoring base off of pybitshares below 0.2.x If we don't merge and test at least the current portion now, it means base refactor is further behind. Can we just merge in base refactor now and then make unit tests to fit the new framework instead of redundant work?

**Comment by PermieBTS** [comment]
So if @joelvai merged this issue 570 and the base refactor, unit tests can then be written using @bitfag docker?

Therefore skipping out the work to complete redundant unit tests in the old style?

If @thehapax pushes their work to codaone/542-base-refactor-notests can it be merged friday 10th of May (Tomorrow)?

**Comment by thehapax** [comment]
I changed the branch - new name is 542-base-refactor-merge, and the pull request is: https://github.com/Codaone/DEXBot/pull/579

**Comment by thehapax** [comment]
@joelvai  you can delete codaone/542-base-refactor-notests this is no longer used.

**Comment by bitfag** [comment]
Versions upgraded.
