### ISSUE TITLE
codacy flagging assert statements in tests

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#571]
For example here https://app.codacy.com/app/thehapax/DEXBot_Codaone/pullRequest?prid=3448821

Related issue https://github.com/fossasia/query-server/issues/332

Solution from the [documentation](https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns):

>To solve flagged valid Python "assert" statements, create a bandit.yml in the root of the repo containing: skips: ['B101']

**Comment by bitProfessor** [comment]
cool
