### ISSUE TITLE
tests naming convention

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#572]
In #561 there is a question raised about how to name tests.

https://docs.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery

Both `test_*.py` or `*_test.py` supported. I prefer 1st, because it looks more consistent with test function names: `test_do_something()`.

We need to pick a single style and use it.

**Comment by joelvai** [comment]
After thinking this more, I suppose it would be better at the beginning.

**Comment by thehapax** [comment]
```test_*.py``` at beginning. to be consistent with methods and ease of identification

**Comment by thehapax** [comment]
I believe we are in agreement with `test` to be a the beginning. Shall we close this issue?
