### ISSUE TITLE
Error when worker is started (windows version)

### ISSUE THREAD

**Issue by Golden-VS** [Codaone/DEXBot#59]
First I successfully downloaded the latest version of the windows package (DEXBot-win64.zip version 1.0.6) and replaced the 2 executables. Then I manually created the config.yml with the default content:

node: wss://bitshares.openledger.info/ws

workers: {}

After starting the Dexbot-gui.exe and creating a worker, this was the content of the config.yml:

node: wss://bitshares.openledger.info/ws

workers: {Worker 1: {account: xxxxxx, market: SMART/BTC, module: dexbot.strategies.relative_orders,
    strategy: Relative Orders, target: {amount: 5.0, center_price: 0.0, center_price_dynamic: true,
      spread: 2.0}}}

Now when i start the worker via the play button, i get the following error in the command screen:

![image](https://user-images.githubusercontent.com/38070098/38304744-ba9cd236-380a-11e8-8a4b-0bee26c52914.png)

**Comment by mikakoi** [comment]
Thanks for reporting this, something critical was forgotten when renaming the relative orders module. I'll release a hotfix soon.

**Comment by Golden-VS** [comment]
I just downloaded the hotfix and tried it again. Now i get another error!

![image](https://user-images.githubusercontent.com/38070098/38309766-1f7a034e-381b-11e8-942b-186c12fb2f70.png)

**Comment by Golden-VS** [comment]
I added a screenshot again to this ticket. there now is another error.

2018-04-04 14:33 GMT+02:00 mikakoi <notifications@github.com>:

**Comment by mikakoi** [comment]
Looks like the problem is that SMART/BTC market is empty, the bot can't properly calculate the center price on empty markets. I suggest you don't use the dynamic center price on empty markets or just try another market that isn't empty.

**Comment by Golden-VS** [comment]
@mikakoi OK, I might know what causes this problem now, but not sure.
SMART is not on bitshares, bit it is on Cryptobridge. So I thought maybe I need to select BRIDGE.SMART/BRIDGE.BTC instead of SMART/BTC
But is this implemented in the code? Should using pairs on child exchanges even work?

If I try this and start DEXBot, the processor spikes and keeps spiking but orders are not placed and i dont get an error message in the command box.

**Comment by Golden-VS** [comment]
OK, I now tried all kind of combinations and I figured that when there is no balance I get an error that I dont have balance, but when I do have balance I always get a high spiking processor after starting. And when i stop I get a crash:

step 1: I press start:
![image](https://user-images.githubusercontent.com/38070098/38390021-5ad22a10-3920-11e8-8522-d41859dac383.png)

step 2: I press stop:
![image](https://user-images.githubusercontent.com/38070098/38389989-43788274-3920-11e8-8fd9-c46dcf38f8f6.png)

**Comment by mikakoi** [comment]
First of all, dexbot does support BRIDGE.SMART/BRIDGE.BTC. During the worker creation you will get an error popup if you try to use a currencies that don't exist. 

As for the problem, are you saying that you aren't getting any orders placed no matter what market you try?

I will look into the crash error.

**Comment by Golden-VS** [comment]
OK, good to know that bridge is supported. 

Yes, I have tried all kinds of combination of coins and markets while having balance for all cases. I have never been even once successful placing a single order.

**Comment by mikakoi** [comment]
I've made a new release (0.1.8) which adds file logging to dexbot. Would you mind downloading the new version and testing if something is logged to dexbot.log when you run a worker?

**Comment by Golden-VS** [comment]
I did, thank you. 
Below my config.yml and dexbot.log. the bot never placed or cancelled any order. I changed the name of my account for privacy reasons.
Config.yml:
node: wss://bitshares.openledger.info/ws

workers: {Worker 1: {account: xxxxxx, market: BRIDGE.SMART/BRIDGE.BTC, module: dexbot.strategies.relative_orders,
    strategy: Relative Orders, target: {amount: 10.0, center_price: 1.215e-05, center_price_dynamic: true,
      spread: 0.5}}}

[dexbot_copy.log](https://github.com/Codaone/DEXBot/files/1886415/dexbot_copy.log)

hope this helps.

**Comment by mikakoi** [comment]
I've located the problem, it seems like you have used 2 different private keys for the same account on dexbot. You can easily fix this by removing the bitshares.sqlite file in `C:\Users\<user>\AppData\Local\ChainSquad GmbH\bitshares` (Or it should be, I don't have a windows machine at hand to check)

I'll create an issue related to this so this can't happen again.

**Comment by MarkoPaasila** [comment]
I guess this issue can be closed

**Comment by Golden-VS** [comment]
well you can close it if you want, in which case i need to wait for the next release.
however, the bitshares.sqlite file does not exist on my computer. also the folder C:\Users\<user>\AppData\Local\ChainSquad GmbH\bitshares does not exist. 
I do have the folder C:\Users\shypo\AppData\Local\Codaone Oy\dexbot and in there, there is the file dexbot.sqlite. deleting this file does NOT wipe my wallet nor does it wipe the worker private key.

**Comment by mikakoi** [comment]
Sorry about that, I just checked the location with a Windows machine. The real path is `C:\Users<user>\AppData\Local\Fabian Schuh\bitshares`. Also, the file that you removed (dexbot.sqlite) does not contain the private keys, it's used to store worker related meta data.

**Comment by Golden-VS** [comment]
Great. Now i was able to wipe the wallet! 
Dexbot places orders and also cancels order. But it is VERY VERY slow. 
I see in the log file these lines:
----------------------
2018-04-12 14:56:43,326 - Worker 1 using account xxxxxxx on BRIDGE.SMART/BRIDGE.BTC - INFO - Canceling all orders
2018-04-12 15:03:23,300 - Worker 1 using account xxxxxxx on BRIDGE.SMART/BRIDGE.BTC - INFO - Placed a buy order for 10.0 BRIDGE.SMART @ 1.2377755148412817e-05
2018-04-12 15:06:47,042 - Worker 1 using account xxxxxxxx on BRIDGE.SMART/BRIDGE.BTC - INFO - Placed a sell order for 10.0 BRIDGE.SMART @ 1.2452245149305971e-05
---------------------------
After the first cancel line appears in the log, it takes almost 10 minutes before the orders actually are cancelled. 
and after the buy order appears in the log it again takes about 4 minutes before this buy order is placed. 
and this slow pace continues...
I have this exact same problem on 3 computers.

Also, creating the first worker (after pressing save button) also takes about 5 minutes. in this time the gui is not responding and processor is high.

**Comment by MarkoPaasila** [comment]
I haven't heard of anyone else testing on Windows yet, which is why he is the first and only.

**Comment by Golden-VS** [comment]
Yes. 2 desktops and 2 laptops  all windows 10 64 bits os. I also tested on Ubuntu 16.04 desktop and this works without problems. All windows machines are slow with all operations.
________________________________

**Comment by Golden-VS** [comment]
Oh and yes i use.1.12 version


________________________________
