### ISSUE TITLE
BitsharesOrderEngine and BitsharesPriceFeed inconsistent attributes

### ISSUE THREAD

**Issue by bitfag** [Codaone/DEXBot#596]
BitsharesOrderEngine uses attributes which are not defined in `__init__` (or elsewhere):

* self.account
* self.market
* self.worker

This means methods which uses these attrs are broken on standalone BitsharesOrderEngine. Now we're don't noticing this because the only user of BitsharesOrderEngine is StrategyBase. All these attrs defined inside StrategyBase.

**Comment by bitfag** [comment]
BitsharesPriceFeed:

* self.market

**Comment by bitfag** [comment]
I think it's a good idea to have this fixed after or at the same time as merging tests for BitsharesOrderEngine and BitsharesPriceFeed.

**Comment by thehapax** [comment]
Yep, we are aware of that. Adding @bitProfessor  to the conversation

**Comment by thehapax** [comment]
Will fix this on next set of pulls.

**Comment by bitProfessor** [comment]
I think it's a good idea to wait until the order engine is updated to the devel branch.

**Comment by bitfag** [comment]
This issue still wasn't addressed properly, looks like without tests it's hard to detect was the fix was right or not.

`BitsharesOrderEngine` in `__init__` sets `self.account = account` while it's still overridden in StrategyBase by property `def account(self)`.

**Comment by thehapax** [comment]
> I think it's a good idea to wait until the order engine is updated to the devel branch.
it is now merged into the devel @bitProfessor 

@bitfag perhaps we should remove all overriding properties in StrategyBase, is this what you mean?

**Comment by thehapax** [comment]
@bitfag i made the changes, see https://github.com/thehapax/DEXBot/tree/596-properties

**Comment by bitfag** [comment]
Not sure, I'd rather wait for tests to clearly see everything working as it should.

**Comment by bitProfessor** [comment]
Ok




| |
bitprofessor
邮箱：bitprofessor@163.com
|

Signature is customized by Netease Mail Master

On 06/20/2019 16:19, Vladimir Kamarzin wrote:

Not sure, I'd rather wait for tests to clearly see everything working as it should.
