### ISSUE TITLE
Using windows package get error "An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call"

### ISSUE THREAD

**Issue by juhanihaapala** [Codaone/DEXBot#60]
Found this issue related https://github.com/seLain/mattermost_bot/issues/19

Could maybe try newer version of python if that would work for packaging

**Comment by imDiver** [comment]
I'm using the latest version 3.7.0b2, there is an error.  WinError 10042, Win8 x64, Python 3.7.0b2
