### ISSUE TITLE
Charting and Visualisation standard for DEXBot

### ISSUE THREAD

**Issue by PermieBTS** [Codaone/DEXBot#604]
In order to have a consistent charting library standard for DEXBot and to keep ongoing maintenance low should Altair be used?

For handling chart data Pandas should be used

EDIT: 
TL;DR - Use DASH plot.ly and Pandas dataframes

**Comment by thehapax** [comment]
@PermieBTS adding @joelvai here, so he can give any feedback on PyQT5 integration with charting libraries. Thanks.

**Comment by joelvai** [comment]
With quick research the Altair seems to be the best solution for this at the moment.

**Comment by PermieBTS** [comment]
Gabriel has some comments about charting libraries we should use. Ive invited him to comment here

**Comment by Jackodb** [comment]
I really recommend https://pywebview.flowrl.com/guide/ which allows you to chart in https://www.chartjs.org/ and use HTML and CSS. I've been using it ever since I started on the visualisation job and liked very much.

**Comment by MarkoPaasila** [comment]
If we display the charts using qtwebview, it probably doesn't matter too much which toolkit we use to generate the html/css/js, or does it?

**Comment by gabev** [comment]
pandas and Matplotlib widgets for obvious reasons ....binding a slider to the spread, increment, orders size, etc  so the orders can be viewed as bars and dynamically adjusted ...when the spread slider is moved, the bars representing the orders in mountain, valley and neutral view will move accordingly in real time ( not preset as I saw in altair) .... when the increment slider is moved , the bars will increase/decrease ...same for the order size ...when the amount of a token is modified the bar adjust dynamically , in real time, up and down... no objection to Altair if we can implement this functionality ...

**Comment by thehapax** [comment]
http://dygraphs.com/gallery/#g/dynamic-update

**Comment by thehapax** [comment]
Also see https://www.highcharts.com/demo/?example=dynamic-update&theme=default

there is a creative commons license for non-commercial products. its also geared toward financial applications which need the dynamic update.

**Comment by JRizzly** [comment]
Roger, I will be implementing. Please ref here for those following: https://github.com/JRizzly/BitsharesRealTimeAccountTracker

**Comment by gabev** [comment]
Here is a quick code example of the functionality...

`
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

fig,ax = plt.subplots()

labels = ['bitCNY','BTS']
colors = ['green','red']
values = np.random.normal(0,1,size=(1000,))
threshold = 0.

axcolor = 'lightgoldenrodyellow'
axthreshold = plt.axes([0.2, 0.001, 0.65, 0.03], facecolor=axcolor)
sthreshold = Slider(axthreshold, 'Increment:', -1., 1., 
                    valinit=threshold, valstep=None)


def update(val):
    data = [np.sum(values <= val), np.sum(values > val)]
    ax.clear()
    ax.bar(labels, data, color=colors)
    thr_txt = ax.text(0.5, 0,  '{:.2f}'.format(val))
    good_label = ax.text(0,data[0], 'Total Buy Orders={:d} bitCNY'.format(data[0]), ha='center')
    bad_label = ax.text(1,data[1], 'Total Sell Orders={:d} BTS'.format(data[1]),ha='center')
    fig.canvas.draw_idle()
sthreshold.on_changed(update)
update(threshold)   

`
I hope we can achieve that.

**Comment by thehapax** [comment]
> Roger, I will be implementing. Please ref here for those following: https://github.com/JRizzly/BitsharesRealTimeAccountTracker

 For your get content do something like:

```
def getContent(url, query_params):                                                                                                                   
    rContent  = ""                                                                                                                                   
    try:                                                                                                                                             
        r = requests.get(url, params=query_params)                                                                                                   
        rContent = json.loads(r.content)                                                                                                             
        debug("HTTP Response",  r.status_code)                                                                                                       
    except Exception as e:                                                                                                                           
        print("GetContent(): error trying to get data...aborting: ")                                                                                 
        print(e)                                                                                                                                     
    return rContent   
```

And put the data you received into a Pandas Dataframe to parse it more efficiently instead of writing loops around arrays:
```
import pandas as pd 

content = getContent(url, query_params)                                                                                                      
df = pd.DataFrame(content) 
```

**Comment by thehapax** [comment]
> If we display the charts using qtwebview, it probably doesn't matter too much which toolkit we use to generate the html/css/js, or does it?

@MarkoPaasila No it doesn't really. Some people really like one or the other. The only criteria I would strongly advocate  on is this: visuals have to look really good or as a new end-user I would not use the software in 2019. If the graphics make it looks like code was written in 2002, then it probably is already out of date, even if it isn't.  That wouldn’t be a good impression for onboarding new dexbot users. Matplotlib sounds like Gabriel's favorite, and is a time tested plotting library but to me it is dated, difficult at times and doesn't look modern. 

Plot.ly and dash look great but I believe have licensing issues. (someone should double check this). Some of the other js libraries mentioned above were sent to me by a friend who is a well established front end JS dev, who also built this as a side project: https://mempool.space/ Further, his advice would be to spend a little time testing out several libraries with a small example that uses the same backend code, and select one that works best with our use case(s) before making a final decision. To that end, as Gabriel pointed out, we'll also need to factor in what libraries are able to handle dynamic updates, and to what degree do we need these features for dexbot financial charting?

**Comment by gabev** [comment]
Grafana Dashboard is open source ....https://grafana.com/

**Comment by gabev** [comment]
Bokeh, Datashader and Holoviews ... also

**Comment by PermieBTS** [comment]
It seems that plot.ly is open source and we could use it.
The charts are very pretty imo

Plot.ly 
The python library is free and is published under the MIT-License https://github.com/plotly/plotly.py/blob/master/LICENSE.txt

The JS-libs are published under the MIT-License since 2015 https://github.com/plotly/plotly.js/blob/master/LICENSE

Link to the open-source announcement of plotly.js from 2015 https://plot.ly/javascript/open-source-announcement/

In the open-source announcement there is also this information about the other librarys of plotly:
The R, Python, and MATLAB clients for Plotly have always been open-source, while the core graphics layer—plotly.js—was closed-source. Now the entire stack is open-source. 

The Accounts you can create on their website are just to host graphs online. Like with a free account you can host one private graph, with a professional account you can host unlimited private/public graphs: https://plot.ly/products/cloud/

**Comment by thehapax** [comment]
> The Accounts you can create on their website are just to host graphs online. Like with a free account you can host one private graph, with a professional account you can host unlimited private/public graphs: https://plot.ly/products/cloud/

See tested examples and please view my notes about plot.ly in the README.md here: 
https://github.com/thehapax/plotly-template

If you use the standard library as used in all example code: 
 ``` import plotly.plotly as py```

the data is automatically made world readable unless one uses the offline library and sets to private in config.  Also, do dexbot users want to host all their data on the plot.ly website?

**Comment by PermieBTS** [comment]
Thanks octo, ive asked @joelvai to take a detailed look

Visualisations are a great PR tool, so we want to encourage users to share their charts/history with DEXBot - but in an anonymous way. If the account name/Identifying features can be separated from the plot.ly data published then I think the free, public hosting on plot.ly would be useful. We may have some power users who want to show their audience their trade history a la trading view and they may use the plot.ly website instead/as well.

Ideally we would want to show % gains/losses so that the specific amount of capital the user has is not detectable. 
I don't think many DEXBot users will want to show others their trade data if they had to display their account name. 
Could the account name be separated from the data? 

I doubt that users will want to pay to host their data privately. A screenshot stored on their local device would serve most purposes would it not?

**Comment by thehapax** [comment]
> Can the visualisers be developed so that it only needs dash localhost?

Yes, but with caveats:
Dash can run a localhost server freely using this example, with real time updates and also interactivity: 
https://dash.plot.ly/live-updates. 

If you run the example above, it will launch on a localhost webserver like so in terminal:
```Running on http://127.0.0.1:8050/
Debugger PIN: 190-509-881
 * Serving Flask app "dash-sat-example" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Running on http://127.0.0.1:8050/
```
I verify that the above  satellite feeds  live-updates example works as a simple public DO droplet deployment. You'll have to figure out a proper deployment though. If you deploy dash on hosts other than localhosts, but this data will be public, but if you want a layer of security (i.e. login so nobody else can find your hosted data) you'll need to use their paid version of deployment or either use a somewhat hacky solution, see below:

- https://community.plot.ly/t/accessing-dash-webserver-from-hosts-other-than-localhost/4675 
- https://sladkovm.github.io/webdev/2017/10/16/Deploying-Plotly-Dash-in-a-Docker-Container-on-Digitital-Ocean.html
- https://dash.plot.ly/deployment and auth limitations for the free version :https://dash.plot.ly/authentication

Further, if we use dash we can bypass javascript as you can do all data viz in dash directly using their libraries and skip js entirely for basic charting (strongly preferred).

pywebview is only needed if you really want to integrate with the existing PyQT5 desktop application, and it is a simple one liner, with the Dash plotting webserver running in the background as http://127.0.0.1:8050/. This would be a no-brainer for integration into the existing PyQT GUI

```
import webview
webview.create_window('Hello world', 'http://127.0.0.1:8050/')
```
I've tested all the examples above and validate they are working as claimed. 

Further with respect to issue #582  (split core from gui), if we are going to create an API based webserver for splitting core from gui/cli access, we'll need to make sure it doesn't collide with the dash server. 

Another way to use dash is just to run the local web server and then have it poll the dexbot-core running in remote aws instance for data. This separation of core and gui would be ideal.

Are there any other criteria we need besides the ones i listed already [here](https://github.com/thehapax/plotly-template/blob/master/README.md)? Please check @PermieBTS @gabev , @joelvai

**Comment by thehapax** [comment]
> I don't think many DEXBot users will want to show others their trade data if they had to display their account name.  Could the account name be separated from the data?

Just run dash locally, nobody else will see data

> I doubt that users will want to pay to host their data privately. A screenshot stored on their local device would serve most purposes would it not?

see above response.
 
> If plot.ly/dash is running on localhost and the data is being input from the BitShares blockchain then the visualisations can be displayed on the DEXBot users local machine and need not be published/accessed from anywhere else, right?

correct

> However, if we want the software accessible via server we would have to pay for it.
> If we went this route, would we be creating another bitshares block explorer? I'm probably wrong but 
he only reason I can see that we wouldn't just want dash to run locally is so that any Bitshares user could enter their account name and chart their trade history. Which isn't really what we're building. We want DEXBot workers progress to be visualised.

Only reason to run dash on remote server is if they want everything remote access for their dexbot instance. I don't see what this has to do with the Bitshares block explorer.  the issue is more about protecting the data on a remote server that could be served to the public. see previous comment about authentication and deployment.

**Comment by thehapax** [comment]
you can see the dash live satellite update code from this page https://dash.plot.ly/live-updates 

temporarily running on my digital ocean instance here: http://104.236.174.201:8050/

I'll leave it there for a few days. The update to the chart is fairly slow but you can see the chart dynamically move on each tick.

**Comment by Jackodb** [comment]
Not sure whether it has been decided to use DASH/Plotly for all the visualisation stuff. Could you please confirm? I have been using the pywebview api with HTML/CSS/JS (chartjs) up until now and it works like a charm. I'm not sure what kind of advantages DASH/Plotly offers us opposed to the method I have been using. I was wondering since I saw the following documentation:
https://github.com/Codaone/DEXBot/wiki/New-Contributors-Guide#visualizations-style-guideline

**Comment by PermieBTS** [comment]
Yes I can confirm the standard is now to use DASH/Plotly and panda dataframes

**Comment by Jackodb** [comment]
So only DASH libraries are permitted, not Chartjs? I made the following app in Chartjs, of which I shared a screenshot a few weeks ago:
https://github.com/Jackodb/visualisation

**Comment by PermieBTS** [comment]
Only DASH libraries
