### ISSUE TITLE
RO: Last market trade as new center price

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#611]
Last own trade (filled order) price as the new center price - as an option for center price source. Choosing this would discard other center price sources, but similarly work in combination with offset and order size options.

This is very simple. I also think it will improve performance - especially in trending markets - and make it harder to manipulate.

**Comment by thehapax** [comment]
if you can also take a look at https://github.com/Codaone/DEXBot/issues/589#issuecomment-497143415, would be appreciated. I'd like to see the init()  not handle order placement

**Comment by MarkoPaasila** [comment]
@thehapax that's unrelated, so I don't want to touch it right now. This new method doesn't add any order placement into init.

But to continue on the topic, how would you like to see things that only need to be done at startup done? They will take the same amount of time whether they are done in init or not.
