### ISSUE TITLE
[multiple workers same account] staggered order + relative order on same pair

### ISSUE THREAD

**Issue by bitcoinsfacil** [Codaone/DEXBot#625]
## Expected Behavior
Relative order (RO) configuration closes orders when the worker stops. Staggered orders (SO) are configured to remain open even if a worker is stopped. 

Not sure if this is a Bug but something to notice or try to avoid= two workers on the same pair with different strategies will have unexpected behavior 

## Actual Behavior
Two workers on the same trading pair: one with RO the other with SO
When stopping/starting a RO worker every order on the pair is canceled. This closes also the SO

## Steps to Reproduce the Problem

  1. Account AB with a worker configured with strategy RO on pair XXX/YYY
  2. Same account AB with a worker configured with strategy SO on pair XXX/YYY
  3. Stop worker with strategy RO

## Specifications

  - Version: command line built on branch `multiple-workers-same-account`
  - OS: ubuntu 16

**Comment by bitfag** [comment]
Related to #434.

This needs to be checked & fixed + test added.

**Comment by bitfag** [comment]
This was checked before release and special unittest `test_mwsa_orders_cancel` was developed.
