### ISSUE TITLE
Unable to access GUI due to bad node

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#628]
The node selection isnt skipping bad nodes, I got kicked out of the DEXBot GUI then was unable to get back into it because the bad node was not being skipped. For GUI users this is no good.
Either need to make sure that we are moving on to the next node or need to be able to get into DEXBot before node selection happens so we can switch from there.

Also, users shouldnt be getting kicked out of DEXBot for bad nodes, it should just switch to another. Many opportunities could be missed in this time.

The node appeared to be completely down as it wasnt listed on the DEX rather than it having a high latency, not sure if that makes any difference?

**Comment by juhanihaapala** [comment]
The gui part is duplicate for this https://github.com/Codaone/DEXBot/issues/603

But skipping dead node is new.

**Comment by joelvai** [comment]
@CryptoKong have you tested if this problem persists with the current devel? I fixed a GUI connection problem recently. Can you tell me the node you were using in case this is still a problem so we can test it.

**Comment by thehapax** [comment]
#635 allows for sorting nodes and skipping ones unreachable on cli. needs to be integrated into GUI

**Comment by thehapax** [comment]
closing for now as per latest merge. if problem reopen.
