### ISSUE TITLE
[command-line] unable to choose values for threshold and % of asset

### ISSUE THREAD

**Issue by bitcoinsfacil** [Codaone/DEXBot#629]
## Actual Behavior
Not showing option when configuring staggered orders to input operational_percent_base: & operational_percent_quote: 

## Steps to Reproduce the Problem

  1. Run configure from cli

**Comment by bitfag** [comment]
This feature is currently available on **single-account-multiple-workers** branch. I checked it and these options are available from cli configure.

**Comment by bitcoinsfacil** [comment]
I understand but was told that `multiple workers on single account` was enabled on the master branch also @bitfag. Then everything is OK
