### ISSUE TITLE
Relative Orders GUI Worker Config Window too large for screen

### ISSUE THREAD

**Issue by PermieBTS** [Codaone/DEXBot#645]
## Expected Behavior
On Windows: Launch DEXBot, login to uptick, Add worker, Configure RO worker settings, Press "save"

## Actual Behavior
On Windows: Launch DEXBot, login to uptick, Add worker, Configure RO worker settings, the window is too big and cant be moved; the "save" button is off-screen and can't be clicked.
1680x1050 also has same issue

## Steps to Reproduce the Problem

  1. Windows 10
  2. Both Resolution 1920x1080 and 1680x1050
  3. 

Staggered Orders was ok

## Specifications

  - Version: 0.13.3
  - OS: Windows 10

I tried changing the DPI settings by right-clicking on the dexbot windows shortcut but nothing so far has solved the issue

**Comment by joelvai** [comment]
What display scaling do you have in display settings? `Settings -> System -> Display -> Scale and layout`. I was able to reproduce this when changing scaling from 100% -> 150% using 1920 x 1080.

**Comment by PermieBTS** [comment]
Solved by right-clicking on DEXBot desktop shortcut > properties > compatibility > open advanced scaling settings > entering a custom scaling size of 100%

Thanks joel
