### ISSUE TITLE
Syntax error in dexbot/ui.py

### ISSUE THREAD

**Issue by pigloo** [Codaone/DEXBot#656]
```
click.echo(f"Checking for nearest nodes with timeout < {timeout} sec....")
                                                                            ^
SyntaxError: invalid syntax
```

**Comment by PermieBTS** [comment]
Could you describe what you tried to do when you got this error?

And ideally post a log file?

**Comment by joelvai** [comment]
What python version are you running?

**Comment by thehapax** [comment]
this error typically happens when trying to use a lower version of python. f-strings is in python 3.6 or higher. For running dexbot we recommend at least 3.6.7+ If you get this error its likely the version of python is below 3.6

**Comment by pigloo** [comment]
This error occurred when installing on a Raspberry Pi using the instructions here: https://github.com/Codaone/DEXBot/wiki/Setup-guide-for-Raspberry-Pi

I was able to continue the installation by removing the 'f' infront of the string

next time i will try upgrading python
