### ISSUE TITLE
RO-price out of range

### ISSUE THREAD

**Issue by froooze** [Codaone/DEXBot#669]
## Expected Behavior
Suited price for RO

## Actual Behavior
price 1000 times higher as it should

## Steps to Reproduce the Problem
1. Asset balance: 1BTS : 0 CNY
2. Asset balance: 0.5BTS : 0.5 CNY

```
RO using account bot on BTS/CNY - INFO - Placing a buy order with 0.1312 CNY @ 328.93864340
RO using account bot on BTS/CNY - INFO - Placing a sell order with 0.53832 BTS @ 342.09618913
RO using account bot on BTS/CNY - INFO - Done placing orders
RO using account bot on BTS/CNY - INFO - Canceling all orders
RO using account bot on BTS/CNY - INFO - Orders canceled
RO using account bot on BTS/CNY - INFO - Placing a buy order with 0.1299 CNY @ 328.31432665
RO using account bot on BTS/CNY - INFO - Placing a sell order with 0.54264 BTS @ 341.44689972
RO using account bot on BTS/CNY - INFO - Done placing orders
RO using account bot on BTS/CNY - INFO - Canceling all orders
RO using account bot on BTS/CNY - INFO - Orders canceled
RO using account bot on BTS/CNY - INFO - Placing a buy order with 0.1286 CNY @ 328.34244411
RO using account bot on BTS/CNY - INFO - Placing a sell order with 0.54691 BTS @ 341.47614188
RO using account bot on BTS/CNY - INFO - Done placing orders
RO using account bot on BTS/CNY - INFO - Canceling all orders
RO using account bot on BTS/CNY - INFO - Orders canceled
RO using account bot on BTS/CNY - INFO - Placing a buy order with 0.1273 CNY @ 328.36984649
RO using account bot on BTS/CNY - INFO - Placing a sell order with 0.55113 BTS @ 341.50464035
RO using account bot on BTS/CNY - INFO - Done placing orders
RO using account bot on BTS/CNY - INFO - Canceling all orders
RO using account bot on BTS/CNY - INFO - Orders canceled
RO using account bot on BTS/CNY - INFO - Placing a buy order with 0.1260 CNY @ 328.39663875
RO using account bot on BTS/CNY - INFO - Placing a sell order with 0.55531 BTS @ 341.53250430
RO using account bot on BTS/CNY - INFO - Done placing orders
RO using account bot on BTS/CNY - INFO - Canceling all orders
RO using account bot on BTS/CNY - INFO - Orders canceled
RO using account bot on BTS/CNY - INFO - Placing a buy order with 0.1248 CNY @ 0.27997230
RO using account bot on BTS/CNY - INFO - Placing a sell order with 0.55944 BTS @ 0.29117119
RO using account bot on BTS/CNY - INFO - Done placing orders
```

## Specifications
                    │ amount: 1.0                                                
                    │ center_price: 0.1                                          
                    │ center_price_depth: 999999.0                               
                    │ center_price_dynamic: True                                 
                    │ center_price_from_last_trade: True                         
                    │ center_price_offset: True                                  
                    │ custom_expiration: False                                   
                    │ dynamic_spread: False                                      
                    │ dynamic_spread_factor: 1.0                                 
                    │ expiration_time: 157680000                                 
                    │ external_feed: False                                       
                    │ external_price_source: gecko
                    │ fee_asset: BTS                                             
                    │ manual_offset: 0.0                                         
                    │ market: BTS/CNY                                            
                    │ market_depth_amount: 10000.0                               
                    │ module: dexbot.strategies.relative_orders                  
                    │ partial_fill_threshold: 90.0                               
                    │ price_change_threshold: 2.0                                
                    │ relative_order_size: True                                  
                    │ reset_on_partial_fill: True                                
                    │ reset_on_price_change: False                               
                    │ spread: 4.0             

  - Version: 0.15.5
  - OS: Ubuntu server 18.04

**Comment by bitfag** [comment]
Need to find what exact settings caused such price shift. Check `center_price_offset: True`. Add more debug to RO.

**Comment by bitfag** [comment]
> center_price_from_last_trade: True

Assuming this was caused by bugs related to CP from last trade (fixed).
