### ISSUE TITLE
Cant get worker to place order

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#67]
[dexbot.log](https://github.com/Codaone/DEXBot/files/1891671/dexbot.log)

**Comment by CryptoKong** [comment]
I may have originally used the wrong key so I inputted "uptick wipewallet" in terminal to remove keys and then used the active private key but still getting the same error.

**Comment by mikakoi** [comment]
It seems like you're using the cryptography library but an old version of it. You can either remove cryptography using `pip uninstall cryptography` (since it's not required by the project) or you can upgrade cryptography with `pip install cryptography --upgrade`

**Comment by CryptoKong** [comment]
It would't let me do that as cryptography wasn't installed, if i try and install cryptography I get an error, not sure if that helps as you say its not needed...
I used "uptick wipewallet" started again and getting same problem

[dexbot.log](https://github.com/Codaone/DEXBot/files/1893812/dexbot.log)

![screenshot from 2018-04-10 09-50-14](https://user-images.githubusercontent.com/33036236/38546438-996816b8-3ca4-11e8-8518-7383dfa21ce9.png)

**Comment by MarkoPaasila** [comment]
@mikakoi apparently installation has been done with install-user, so should cryptography be upgraded with a -user switch too?

**Comment by mikakoi** [comment]
No, even if it was installed with --user switch, pip should be able to at least find the package when upgrading. I need to investigate this a bit more.

**Comment by lunedio** [comment]
I had the exact same problem and `pip3 install cryptography --user --upgrade` worked instead of `pip install cryptography --upgrade` Thanks!

**Comment by MarkoPaasila** [comment]
I wonder why I didn't have this issue even on a fresh install using the same commands (likely). Did @lunedio or @CryptoKong install uptick or something else separately?

**Comment by lunedio** [comment]
No, only what we needed for the node.

**Comment by mikakoi** [comment]
@CryptoKong can you run `pip list` and paste the results here?

**Comment by CryptoKong** [comment]
DexBot is now placing orders for me too after using `pip3 install cryptography --user --upgrade`
Thanks for your help :)

**Comment by MarkoPaasila** [comment]
Maybe the solution was to use pip3 instead of pip, rather than the --user switch. Ubuntu 16.04 defaults to pip2

**Comment by mikakoi** [comment]
Yeah I forgot that pip defaults to pip2 on Ubuntu. Since it's fixed now, I'll close this issue.

**Comment by hiquanta** [comment]
thans!  it works!
