### ISSUE TITLE
KOTH with one asset

### ISSUE THREAD

**Issue by froooze** [Codaone/DEXBot#670]
## Expected Behavior
No error

## Actual Behavior
Error because bot has only one asset:

```
2019-08-26 15:11:50,352 INFO Context impl SQLiteImpl.
2019-08-26 15:11:50,353 INFO Will assume non-transactional DDL.
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=51 time=1.28 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.281/1.281/1.281/0.000 ms
dexbot - INFO - Dexbot version 0.15.5, logfile: /home/ubuntu/.local/share/dexbot/dexbot.log
bot using account bot on BTS/CNY - INFO - Initializing King of the Hill...
bot using account bot on BTS/CNY - INFO - Canceling all orders
bot using account bot on BTS/CNY - INFO - Orders canceled
bot using account bot on BTS/CNY - INFO - King of the Hill initialized.
bot using account bot on BTS/CNY - ERROR - Cannot place buy order with 0 amount. Adjust your settings!
bot using account bot on BTS/CNY - INFO - Placing a sell order with 0.97947 BTS @ 0.28586889
bot using account bot on BTS/CNY - ERROR - Worker "bot" is disabled
```

## Steps to Reproduce the Problem                               
                    │ buy_order_amount: 1.0                                      
                    │ buy_order_size_threshold: 1.0                              
                    │ fee_asset: BTS                                             
                    │ lower_bound: 0.1                                           
                    │ market: BTS/CNY                                            
                    │ min_order_lifetime: 6                                      
                    │ mode: both                                                 
                    │ module: dexbot.strategies.king_of_the_hill                 
                    │ relative_order_size: True                                  
                    │ sell_order_amount: 1.0                                     
                    │ sell_order_size_threshold: 1.0                             
                    │ upper_bound: 1.0 

## Specifications

  - Version: 0.15.5
  - OS: Ubuntu Server 18.04

**Comment by bitfag** [comment]
If you're operating in `mode: both` it's supposed you have both BASE and QUOTE assets. If only one asset available, mode should be set to "buy" or "sell".

Though for convenience we can wait until sell order fills so BASE asset become available and place both orders after this.
