### ISSUE TITLE
GUI button "Modify Worker" works only once, than raising "AttributeError: __getattribute__" exception

### ISSUE THREAD

**Issue by vereten** [Codaone/DEXBot#678]
## Actual Behavior
GUI button "Modify Worker" works only once, than raising "AttributeError: __getattribute__" exception and "edit worker window" is incomplete than(take look at screenshot).

Also "Add worker" button with same behavior.

To edit multiple relative strategy workers application needs to be restarted as many times as edits that is very annoying.

Turn on/off buttons on workers works well. Staggered workers edit works well.

## Steps to Reproduce the Problem

  1. start dexbot-gui
  2. unlock dexbot
  3. add some relative strategy worker and save it
  3. click on "Modify Worker" and close "Edit window"
  4. click on "Modify Worker" or "Add worker" second time and exeption will rise

## Specifications

  - Version: 0.15.5
  - OS: Debian

## Screenshots

![002](https://user-images.githubusercontent.com/11050858/64241606-5d153300-cf04-11e9-8d26-994cdc872245.png)
![001](https://user-images.githubusercontent.com/11050858/64241607-5dadc980-cf04-11e9-95cb-010e89cb0faf.png)
![003](https://user-images.githubusercontent.com/11050858/64241605-5d153300-cf04-11e9-91c9-914f93dcd2c8.png)

## Full expection

AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/.local/lib/python3.7/site-packages/dexbot-0.15.5-py3.7.egg/dexbot/views/errors.py", line 94, in func_wrapper
    return func(*args, **kwargs)
  File "/home/username/.local/lib/python3.7/site-packages/dexbot-0.15.5-py3.7.egg/dexbot/controllers/worker_controller.py", line 110, in change_strategy_form
    self.view.strategy_widget = StrategyFormWidget(self, strategy_module, worker_data)
  File "/home/username/.local/lib/python3.7/site-packages/dexbot-0.15.5-py3.7.egg/dexbot/views/strategy_form.py", line 28, in __init__
    self.strategy_widget.setupUi(self)
  File "/home/username/.local/lib/python3.7/site-packages/dexbot-0.15.5-py3.7.egg/dexbot/views/ui/forms/relative_orders_widget_ui.py", line 1021, in setupUi
    QtCore.QMetaObject.connectSlotsByName(Form)
SystemError: <built-in function connectSlotsByName> returned a result with an error set

**Comment by PermieBTS** [comment]
Re-installing might solve the problem, but I know that is a pain.

Could you try modifying with cli and see if you get the same error?

Quit the GUI

$ cd dexbot (or the folder which you've installed dexbot into)
$ dexbot-cli configure
Follow the setup guide

When you go through the cli configure menu you will be asked to set parameters for everything even if you said "no" to using them. Just input valid parameters, but the as long as you said "no" to using the feature it won't be used.

**Comment by vereten** [comment]
I removed whole ~/dexbot  also ~/.local/bin also ~/.local/lib ~/.local/share/bitshares+dexbot and problem still happening :( 

cli works fine but its psycho to use, rather to edit ~/.config/dexbot/config.yml

**Comment by PermieBTS** [comment]
@bitfag are you able to look into this?

**Comment by PermieBTS** [comment]
@vereten could you post the full error log so we can see what's going on in full?

**Comment by vereten** [comment]
It seems like some libs updated and this started happening. Im not sure maybe its debian related only. Last time some new depends installed by make, ~/.local/lib/python3.6 and now there i can see also python3.7

**Comment by vereten** [comment]
@PermieBTS which log file do you need?
I posted full exeption above.
Running from console no errors or information appear.

**Comment by PermieBTS** [comment]
Yes sorry, I missed that at the end of your post. 

Don't need anything else, thanks

**Comment by bitfag** [comment]
Should be fixed in further PyQT releases https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042026.html

@vereten as a workaround, you can downgrade python to 3.6.x version

**Comment by vereten** [comment]
> Should be fixed in further PyQT releases https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042026.html
> 
> @vereten as a workaround, you can downgrade python to 3.6.x version

Ok, how can i tell dexbot build system to install python version 3.6 instead of 3.7 ?

**Comment by bitfag** [comment]
Dexbot doesn't manages python versions, you need to install python 3.6 somehow first, then it could be used by tool like `virtualenv --python=...`

**Comment by bitfag** [comment]
Closing as we're not experiencing this on ubuntu.
