### ISSUE TITLE
OSX version doesn't run on an older version such as El Capitan

### ISSUE THREAD

**Issue by rsswlkr** [Codaone/DEXBot#693]
## Expected Behaviour
Launch application on minimum version OSX 10.11.x 
Scenario: user has an older macbook laying around, and wants to use it to run DEXBot. Some models even just a few years old, (and macbook pro can last a very long time) won't upgrade to latest Apple OSX so it would be nice to have version of the app compiled to support such machines. 

## Actual Behaviour (When launching on command line output is seen, screenshot from opening as double click attached)
[18963] Error loading Python lib '/var/folders/pt/2740_3w93_j401bt8nfl08s00000gn/T/_MEIDr2QpV/Python': dlopen: dlopen(/var/folders/pt/2740_3w93_j401bt8nfl08s00000gn/T/_MEIDr2QpV/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/pt/2740_3w93_j401bt8nfl08s00000gn/T/_MEIDr2QpV/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/pt/2740_3w93_j401bt8nfl08s00000gn/T/_MEIDr2QpV/Python

## Steps to Reproduce the Problem

  1. Install on a version of OSX older than that which was used to compile the dist
  2. Try to launch the app
  3. Problems seen as above

## Specifications

  - Version:
  - OS: OSX 10.11.6 El Capitan

Possible known workarounds: 
1) https://github.com/pyinstaller/pyinstaller/issues/1191
2) https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=11&cad=rja&uact=8&ved=2ahUKEwi-7ceM26flAhUIpI8KHY0aDU0QFjAKegQIBRAB&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F14747788%2Fpy2app-compile-app-for-older-mac-versions&usg=AOvVaw3R2DyVep5Qw3ysO4ESlbYI

![dexbot-osx-error](https://user-images.githubusercontent.com/28939873/67139181-628dc900-f277-11e9-8432-e2447b161ce0.png)
Attached: When trying to launch GUI from Finder

**Comment by PermieBTS** [comment]
Hi @rsswlkr 
We can get some a Mac install for older versions, but right now the focus is on CEX-DEX arb and there is limited dev availability for other things.

In the meantime are you able to run a Virtual Machine using virtualbox to install DEXBot via Ubuntu 18.04?

I'm sure you know this already but for others who may be reading here is a guide for installing Virtualbox to run Ubuntu 18.04 on Mac: https://www.dev2qa.com/how-to-install-ubuntu-on-virtualbox-mac/

Then DEXBot can be installed on Ubuntu using this section of the wiki: https://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Ubuntu-Linux

**Comment by thehapax** [comment]
@rsswlkr @PermieBTS  The oldest version of Dexbot that was tested for install is OSX 10.12.  If you can upgrade to that version it would be ideal, and the instructions are in the Wiki. 

**CAVEAT. Make sure you have the proper version of python installed, that is the one from brew install, or python.org **

**DO NOT USE THE DEFAULT VERSION INCLUDED ON YOUR MAC**
The way to check is to make sure in the Terminal shell 
$ which -a python3 
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3

it should not say otherwise or this is the incorrect version of python. The default mac python is incompatible with running dexbot, especially all of its dependencies. 

Wiki instructions here: https://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Mac-OS-X-10.12-or-higher

**Comment by thehapax** [comment]
Ideally you are running dexbot on Python 3.6.8 or higher. due to the new packages added to dexbot it cannot run below python 3.6

**Comment by thehapax** [comment]
@rsswlkr In your error message posted, the version of python you are running is not compatible for OSX 10.11, its built for 10.13. See your own error message posted:

> Referenced from: /var/folders/pt/2740_3w93_j401bt8nfl08s00000gn/T/_MEIDr2QpV/Python (which was built for Mac OS X 10.13)

**Comment by PermieBTS** [comment]
https://docs.python-guide.org/starting/install3/osx for installing python for use by DEXBot

**Comment by rsswlkr** [comment]
All above done including python. It might be possible to build from source and add the package libs missing instead. For this particular Apple computer it is a MacBook Pro from 2009 ... hence it won't update past El Capitan. A better way indeed does seem to be using the VM or dedicated Ubuntu installation. Build for older OS versions is a nice to have ...
