### ISSUE TITLE
Setup Guide needs a guide

### ISSUE THREAD

**Issue by ioBanker** [Codaone/DEXBot#696]
The DEXBOT installation procedure for dexbot-cli was unclear to me and very confusing.
 
Required packages should be scoped and referred in a single install command.
 
Required steps should be included.

Operating system compatibility should be clarified.

Some of commands are referring to pip while others are referring to pip3.

Its unclear which version of python is compatible within the document.

Reference: https://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Ubuntu-Linux

**Comment by PermieBTS** [comment]
Did you try 

**18.3.1** If you just want the CLI version without graphics (which will work on more systems):

```
$ sudo apt-get install gcc make libssl-dev python3-pip python3-dev git
$ git clone https://github.com/Codaone/DEXBot.git dexbot
$ cd dexbot   
$ pip3 install --user -e .                  (the dot included)
```
Possible Additional Needed Commands:
```
$ pip3 install --user pyqt5
$ sudo apt-get install python3-pyqt5
$ sudo apt-get install pyqt5-dev-tools
$ sudo apt-get install qttools5-dev-tools
$ sudo apt-get install -y software-properties-common
$ sudo add-apt-repository universe
$ pip install -r requirements.txt
```

?
```
$ pip install -r requirements.txt
```

Installs all the required packages in a single command

**Comment by ioBanker** [comment]
I have enhanced the installation procedure at https://github.com/Codaone/DEXBot/wiki/Setup-Guide-for-Ubuntu-Linux

Issue can be closed.
