### ISSUE TITLE
During the Ubuntu installation it cannot find some tags or branches referred in requirements.txt

### ISSUE THREAD

**Issue by ioBanker** [Codaone/DEXBot#698]
## Actual Behavior
  Cloning https://github.com/Codaone/python-bitshares.git (to 0c9bf5ef3808572b7a10dfc32615906083e6b8ff) to /tmp/pip-build-oe0tythi/bitshares
  **Could not find a tag or branch '0c9bf5ef3808572b7a10dfc32615906083e6b8ff', assuming commit.**

  Cloning https://github.com/Codaone/python-graphenelib.git (to ba3702a25498f56a8ade8b855b812e7ec00311e2) to /tmp/pip-build-oe0tythi/graphenelib
  **Could not find a tag or branch 'ba3702a25498f56a8ade8b855b812e7ec00311e2', assuming commit.**

**Comment by bitfag** [comment]
Correct, it's a commit. Ignore this warning.

**Comment by ioBanker** [comment]
It would give to users a feeling that something is wrong, I'd recommend to hide it.

**Comment by bitfag** [comment]
Agree, better to switch to install from a tag.

**Comment by PermieBTS** [comment]
@joelvai is this your area?

**Comment by bitfag** [comment]
Closing as not an issue. Soon we will switch to upstream libraries - warning should disappear.
