### ISSUE TITLE
AssertionError - Worker cannot be created

### ISSUE THREAD

**Issue by gabev** [Codaone/DEXBot#74]
This happened after the last upgrade to 0.1.12 ...workers cannot be created anymore

![image](https://user-images.githubusercontent.com/9032546/38675403-6e9b4900-3e0c-11e8-9e32-110d369c8bc4.png)

**Comment by MarkoPaasila** [comment]
Apparenly upgraded with `git pull` and `make install-user` in master branch

**Comment by MarkoPaasila** [comment]
I'll close this as it doesn't seem relevant any more.
