### ISSUE TITLE
OpenSSL error again in 0.1.14

### ISSUE THREAD

**Issue by gabev** [Codaone/DEXBot#86]
![image](https://user-images.githubusercontent.com/9032546/38945108-69f2fcb2-42ea-11e8-8193-a1c91c69cb89.png)

**Comment by MarkoPaasila** [comment]
@gabev this doesn't seem to occur any more, or does it? If not, I will close this issue.

**Comment by mikakoi** [comment]
No answer from OP, closing for now.
