### ISSUE TITLE
Only stop Worker with exception, not the whole bot.

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#90]
If you have several Workers, and one experiences some exception like "Unknown order type", suspend the Worker in question and not the whole bot. Otherwise it will be better to run each Worker in a separate session/machine.

**Comment by MarkoPaasila** [comment]
@mikakoi this is done, isn't it?

**Comment by mikakoi** [comment]
No it's not

**Comment by bitfag** [comment]
Closing as this was fixed long ago.
