### ISSUE TITLE
Request: Place links for the binaries or release on README or WIKI

### ISSUE THREAD

**Issue by gibbsfromncis** [Codaone/DEXBot#94]
The issue is first the user sees is:
<img width="394" alt="screenshot 2018-04-24 00 38 13" src="https://user-images.githubusercontent.com/35899973/39156729-cb685e12-4757-11e8-9e2b-8187321f986b.png">

And on Wiki no any info about binaries which users able to download

**Comment by wmbutler** [comment]
I was pretty easy. I downloaded the binaries from the release page and placed it in my applications folder and double clicked it.

**Comment by gibbsfromncis** [comment]
@wmbutler maybe it's developer habit but first of all I read always README and it says: Installing and running the software - [See instructions in the Wiki](https://github.com/Codaone/DEXBot/wiki/Installing-and-Running) and unfortunately there are no any info about binaries to download.

**Comment by MarkoPaasila** [comment]
@gibbsfromncis Thanks for pointing this out. I intend to point users to the binaries once they are tested to work properly. Now there's still one bug in the Windows build, one in the Linux build and OSX is untested. So I have to wait a little.
