### ISSUE TITLE
Which asset are fee's payed with?

### ISSUE THREAD

**Issue by MarkoPaasila** [Codaone/DEXBot#95]
If the account doesn't have any BTS, the fee should be payed with whatever asset is available. Otherwise it will frustrate many new users, especially non-BitShares people. How is this currently handled?

**Comment by mikakoi** [comment]
It seems that python-bitshares has base for adding transaction fee added in https://github.com/bitshares/python-bitshares/pull/56

But it currently does not support adding fee to buy/sell methods. Those need to first implemented before dexbot can utilize them.

**Comment by MarkoPaasila** [comment]
Ok let's put this on hold for a while.

**Comment by MarkoPaasila** [comment]
It was discussed by me and @mikakoi that it would probably be best to contribute the code for paying fee's in any asset to pybitshares, and then make use of it in DEXBot.
